# Generated by Django 4.2.7 on 2024-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0031_alter_regionalheadquarter_requisites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Должность"
            ),
        ),
    ]
