# Generated by Django 4.2.7 on 2024-06-09 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0032_alter_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegionalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_applications', to='headquarters.regionalheadquarter', verbose_name='РШ, в котором была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в РШ')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_applications', to='headquarters.localheadquarter', verbose_name='МШ, в который была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в МШ')),
            ],
            options={
                'verbose_name': 'Заявка на вступление в МШ',
                'verbose_name_plural': 'Заявки на вступление в МШ',
            },
        ),
        migrations.CreateModel(
            name='UserEducationalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_applications', to='headquarters.educationalheadquarter', verbose_name='Обр.штаб, в который была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в обр.штаб')),
            ],
            options={
                'verbose_name': 'Заявка на вступление в обр.штаб',
                'verbose_name_plural': 'Заявки на вступление в обр.штабы',
            },
        ),
        migrations.CreateModel(
            name='UserDistrictApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_applications', to='headquarters.districtheadquarter', verbose_name='Окружной штаб, в котором была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в Окружной штаб')),
            ],
        ),
        migrations.CreateModel(
            name='UserCentralApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_applications', to='headquarters.centralheadquarter', verbose_name='ЦШ, в котором была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в ЦШ')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userregionalapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_regional_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='userlocalapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_local_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='usereducationalapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_eduunique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='userdistrictapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_district_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='usercentralapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_central_unique_constraint'),
        ),
    ]
