# Generated by Django 4.2.7 on 2024-06-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0032_alter_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEducationalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_applications', to='headquarters.educationalheadquarter', verbose_name='Обр.штаб, в который была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в обр.штаб')),
            ],
            options={
                'verbose_name': 'Заявка на вступление в обр.штаб',
                'verbose_name_plural': 'Заявки на вступление в обр.штабы',
            },
        ),
        migrations.AddConstraint(
            model_name='usereducationalapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_eduunique_constraint'),
        ),
    ]
