# Generated by Django 4.2.7 on 2024-06-09 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0033_usereducationalapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_applications', to='headquarters.localheadquarter', verbose_name='МШ, в который была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в МШ')),
            ],
            options={
                'verbose_name': 'Заявка на вступление в МШ',
                'verbose_name_plural': 'Заявки на вступление в МШ',
            },
        ),
        migrations.AddConstraint(
            model_name='userlocalapplication',
            constraint=models.UniqueConstraint(fields=('user', 'headquarter'), name='user_local_unique_constraint'),
        ),
    ]
