# Generated by Django 4.2.7 on 2024-07-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0033_userregionalapplication_userlocalapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercentralheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userdetachmentposition',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userdistrictheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='usereducationalheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userlocalheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userregionalheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
    ]
