# Generated by Django 4.2.7 on 2024-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='name',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='Полное название образовательной организации'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='short_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Короткое название образовательной организации (например, РГГУ)'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
    ]
