# Generated by Django 4.2.7 on 2024-08-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0035_alter_area_name_alter_centralheadquarter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalHeadquarterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.regionalheadquarter', verbose_name='РШ')),
            ],
            options={
                'verbose_name': 'Email Регионального Штаба',
                'verbose_name_plural': 'Email Региональных Штабов',
            },
        ),
    ]
