
volumes:
  static:
  media:
  pg_data:

networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  backend:
    image: d2avids/rso_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/static
      - media:/app/media
    networks:
      - internal
  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./rso_frontend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
