version: '3'

volumes:
  static:
  media:
  pg_data:
  frontend_dist:

networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - internal
  backend:
    build: ./rso_backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - static:/backend_static/static
      - media:/app/media
    networks:
      - internal
  celery_worker:
    build: ./rso_backend
    env_file: .env
    command: celery -A rso_backend worker --loglevel=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - backend
    networks:
      - internal
  celery_beat:
    build: ./rso_backend
    env_file: .env
    command: celery -A rso_backend beat -l info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - celery_worker
    networks:
      - internal
  frontend:
    image: nem1zida/rso_frontend:latest
    env_file: .env
    depends_on:
      - backend
    volumes:
      - frontend_dist:/app/src/app/dist
    networks:
      - internal
  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
      - frontend_dist:/usr/src/app/src/app/dist
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
