version: '3'

volumes:
  static:
  media:
  pg_data:
  frontend_dist:
  logs:

networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - internal
  backend:
    build: ./rso_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./rso_backend:/app
      - ./logs:/app/logs
      - static:/app/collected_static
      - media:/app/media
    networks:
      - internal
    environment:
      - GUNICORN_WORKERS=1
      - GUNICORN_TIMEOUT=60
  celery_worker:
    build: ./rso_backend
    env_file: .env
    command: celery -A rso_backend worker --loglevel=info
    volumes:
      - ./logs:/app/logs
      - ./rso_backend:/app
      - media:/app/media
    depends_on:
      - backend
    networks:
      - internal
  celery_beat:
    build: ./rso_backend
    env_file: .env
    command: celery -A rso_backend beat -l info
    volumes:
      - ./logs:/app/logs
      - ./rso_backend:/app
      - media:/app/media
    depends_on:
      - celery_worker
    networks:
      - internal
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
    ports:
      - "9000:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal