# Generated by Django 4.2.7 on 2025-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время блокировки')),
            ],
            options={
                'verbose_name': 'Заблокированный IP',
                'verbose_name_plural': 'Заблокированные IP',
            },
        ),
    ]
