# Generated by Django 4.2.7 on 2024-07-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalRegionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField(verbose_name='Количество членов регионального отделения')),
                ('employed_sso', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССО')),
                ('employed_spo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СПО')),
                ('employed_oop', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ООП')),
                ('employed_smo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СМО')),
                ('employed_sservo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССервО')),
                ('employed_sses', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССэС')),
                ('employed_specialized_detachments', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, профильные отряды')),
                ('employed_production_detachments', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, производственные отряды')),
                ('employed_top', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, ТОП')),
                ('regional_headquarter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Статистический отчет РШ',
                'verbose_name_plural': 'Статистические отчеты РШ',
            },
        ),
    ]
