# Generated by Django 4.2.7 on 2024-07-18 16:12

import django.db.models.deletion
from django.db import migrations, models

import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('regional_competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('regional_headquarter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 4 показателю',
                'verbose_name_plural': 'Отчеты по 4 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR4Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField(verbose_name='Количество человек, принявших участие в мероприятии')),
                ('start_date', models.DateField(verbose_name='Дата начала проведения мероприятия')),
                ('end_date', models.DateField(verbose_name='Дата окончания проведения мероприятия')),
                ('regulations', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Положение о мероприятии')),
                ('is_interregional', models.BooleanField(default=False, verbose_name='Межрегиональное')),
                ('regional_r4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_competitions.regionalr4', verbose_name='Отчет')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalR4Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на группу мероприятия в социальных сетях')),
                ('regional_r4_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional_competitions.regionalr4event', verbose_name='Мероприятие')),
            ],
        ),
    ]
