# Generated by Django 4.2.7 on 2024-08-06 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('regional_competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount_of_money', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем средств собранных бойцами РО РСО')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан подтверждающего документа')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 12 показателю',
                'verbose_name_plural': 'Отчеты по 12 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('number_of_members', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество членов РО РСО, принявших участие')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан подтверждающего документа')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 13 показателю',
                'verbose_name_plural': 'Отчеты по 13 показателю',
            },
        ),
        migrations.AlterModelOptions(
            name='regionalr5',
            options={'verbose_name': 'Отчет по 5 показателю', 'verbose_name_plural': 'Отчеты по 5 показателю'},
        ),
        migrations.AlterModelOptions(
            name='regionalr5event',
            options={'verbose_name': 'Проект  5-го показателя', 'verbose_name_plural': 'Проекты 5-го показателя'},
        ),
        migrations.AddField(
            model_name='regionalr5event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Общее количество участников'),
        ),
        migrations.AlterField(
            model_name='regionalr101link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на социальные сети/электронные СМИ, подтверждающие проведение акции'),
        ),
        migrations.AlterField(
            model_name='regionalr102link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на социальные сети/электронные СМИ, подтверждающие проведение акции'),
        ),
        migrations.AlterField(
            model_name='regionalr16',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Наличие трудового проекта, в котором ЛО РСО одержал победу'),
        ),
        migrations.AlterField(
            model_name='regionalr16link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на группу проекта в социальных сетях'),
        ),
        migrations.AlterField(
            model_name='regionalr16project',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование проекта, в котором ЛСО РО одержал победу'),
        ),
        migrations.AlterField(
            model_name='regionalr16project',
            name='project_scale',
            field=models.CharField(blank=True, choices=[('Всероссийский', 'Всероссийский'), ('Окружной', 'Окружной'), ('Межрегиональный', 'Межрегиональный')], max_length=30, null=True, verbose_name='Масштаб проекта'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr4link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='ro_participants_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество человек из своего региона, принявших участие в трудовом проекте'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr5link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL-адрес'),
        ),
        migrations.CreateModel(
            name='RegionalR14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('report_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_14', to='regional_competitions.regionalr12', verbose_name='Отчет 12')),
                ('report_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_14', to='regional_competitions.regionalr13', verbose_name='Отчет 13')),
            ],
            options={
                'verbose_name': 'Отчет по 14 показателю',
                'verbose_name_plural': 'Отчеты по 14 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('participants_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество человек, входящих в группу РО РСО в социальной сети "ВКонтакте"')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скриншот численности группы РО РСО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 11 показателю',
                'verbose_name_plural': 'Отчеты по 11 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount_of_money', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма уплаченных членских взносов')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан подтверждающего документа')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 1 показателю',
                'verbose_name_plural': 'Отчеты по 1 показателю',
            },
        ),
    ]
