# Generated by Django 4.2.7 on 2024-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalr5',
            options={'verbose_name': 'Отчет по 5 показателю', 'verbose_name_plural': 'Отчеты по 5 показателю'},
        ),
        migrations.AlterModelOptions(
            name='regionalr5event',
            options={'verbose_name': 'Проект  5-го показателя', 'verbose_name_plural': 'Проекты 5-го показателя'},
        ),
        migrations.AddField(
            model_name='regionalr5event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Общее количество участников'),
        ),
    ]
