# Generated by Django 4.2.7 on 2024-08-06 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import regional_competitions.utils


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0034_alter_usercentralheadquarterposition_position_and_more"),
        ("regional_competitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalR12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлен на верификацию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "verified_by_chq",
                    models.BooleanField(null=True, verbose_name="Верифицирован ЦШ"),
                ),
                (
                    "verified_by_dhq",
                    models.BooleanField(default=False, verbose_name="Верифицирован ОШ"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "amount_of_money",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Объем средств собранных бойцами РО РСО",
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=regional_competitions.utils.regional_comp_regulations_files_path,
                        verbose_name="Скан подтверждающего документа",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 12 показателю",
                "verbose_name_plural": "Отчеты по 12 показателю",
            },
        ),
        migrations.CreateModel(
            name="RegionalR13",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлен на верификацию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "verified_by_chq",
                    models.BooleanField(null=True, verbose_name="Верифицирован ЦШ"),
                ),
                (
                    "verified_by_dhq",
                    models.BooleanField(default=False, verbose_name="Верифицирован ОШ"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "number_of_members",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество членов РО РСО, принявших участие",
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=regional_competitions.utils.regional_comp_regulations_files_path,
                        verbose_name="Скан подтверждающего документа",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 13 показателю",
                "verbose_name_plural": "Отчеты по 13 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="regionalr5",
            options={
                "verbose_name": "Отчет по 5 показателю",
                "verbose_name_plural": "Отчеты по 5 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="regionalr5event",
            options={
                "verbose_name": "Проект  5-го показателя",
                "verbose_name_plural": "Проекты 5-го показателя",
            },
        ),
        migrations.AddField(
            model_name="regionalr5event",
            name="participants_number",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Общее количество участников"
            ),
        ),
        migrations.CreateModel(
            name="RegionalR14",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "report_12",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_14",
                        to="regional_competitions.regionalr12",
                        verbose_name="Отчет 12",
                    ),
                ),
                (
                    "report_13",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_14",
                        to="regional_competitions.regionalr13",
                        verbose_name="Отчет 13",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 14 показателю",
                "verbose_name_plural": "Отчеты по 14 показателю",
            },
        ),
        migrations.CreateModel(
            name="RegionalR11",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлен на верификацию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "verified_by_chq",
                    models.BooleanField(null=True, verbose_name="Верифицирован ЦШ"),
                ),
                (
                    "verified_by_dhq",
                    models.BooleanField(default=False, verbose_name="Верифицирован ОШ"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "participants_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name='Количество человек, входящих в группу РО РСО в социальной сети "ВКонтакте"',
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=regional_competitions.utils.regional_comp_regulations_files_path,
                        verbose_name="Скриншот численности группы РО РСО",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 11 показателю",
                "verbose_name_plural": "Отчеты по 11 показателю",
            },
        ),
        migrations.CreateModel(
            name="RegionalR1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлен на верификацию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "verified_by_chq",
                    models.BooleanField(null=True, verbose_name="Верифицирован ЦШ"),
                ),
                (
                    "verified_by_dhq",
                    models.BooleanField(default=False, verbose_name="Верифицирован ОШ"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "amount_of_money",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Сумма уплаченных членских взносов",
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=regional_competitions.utils.regional_comp_regulations_files_path,
                        verbose_name="Скан подтверждающего документа",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 1 показателю",
                "verbose_name_plural": "Отчеты по 1 показателю",
            },
        ),
    ]
