# Generated by Django 4.2.7 on 2024-07-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('regional_competitions', '0002_regionalr4_regionalr4event_regionalr4link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalr4event',
            options={'verbose_name': 'Мероприятие по 4 показателю', 'verbose_name_plural': 'Мероприятия по 4 показателю'},
        ),
        migrations.AlterField(
            model_name='regionalr4',
            name='regional_headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='regional_r4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='regional_competitions.regionalr4', verbose_name='Отчет'),
        ),
        migrations.AlterField(
            model_name='regionalr4link',
            name='regional_r4_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr4event', verbose_name='Мероприятие'),
        ),
    ]
