# Generated by Django 4.2.7 on 2024-08-03 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import regional_competitions.utils


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0034_alter_usercentralheadquarterposition_position_and_more"),
        ("regional_competitions", "0002_alter_regionalr5_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalR12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлен на верификацию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "verified_by_chq",
                    models.BooleanField(null=True, verbose_name="Верифицирован ЦШ"),
                ),
                (
                    "verified_by_dhq",
                    models.BooleanField(default=False, verbose_name="Верифицирован ОШ"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "amount_of_money",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Объем средств собранных бойцами РО РСО",
                    ),
                ),
                (
                    "scan_file",
                    models.FileField(
                        upload_to=regional_competitions.utils.regional_comp_regulations_files_path,
                        verbose_name="Скан подтверждающего документа",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 12 показателю",
                "verbose_name_plural": "Отчеты по 12 показателю",
            },
        ),
    ]
