# Generated by Django 4.2.7 on 2024-08-12 13:27

import django.db.models.deletion
from django.db import migrations, models

import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0035_alter_area_name_alter_centralheadquarter_name_and_more'),
        ('regional_competitions', '0003_regionalr19_regionalr17'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR91',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Снежный десант РСО"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Снежный десант РСО"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR910',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Всероссийская акция «Вожатский диктант»"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Всероссийская акция «Вожатский диктант»"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR911',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Алгоритмы роста"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Алгоритмы роста"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR92',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Творческий фестиваль"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Творческий фестиваль"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR93',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Спартакиада студенческих отрядов и комплекс мероприятий РСО-спорт"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Спартакиада студенческих отрядов и комплекс мероприятий РСО-спорт"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR94',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Конкурс профессионального мастерства"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Конкурс профессионального мастерства"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR95',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "День РСО"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "День РСО"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR96',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Региональная школа подготовки командиров и комиссаров РСО"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Региональная школа подготовки командиров и комиссаров РСО"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR97',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Открытие трудового семестра"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Открытие трудового семестра"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR98',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Закрытие трудового семестра"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Закрытие трудового семестра"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR99',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 9 показателю - "Окружная школа руководителей штабов студенческих отрядов образовательных организаций"',
                'verbose_name_plural': 'Отчеты по 9 показателю - "Окружная школа руководителей штабов студенческих отрядов образовательных организаций"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR99Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r99', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr99', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Окружная школа руководителей штабов студенческих отрядов образовательных организаций"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Окружная школа руководителей штабов студенческих отрядов образовательных организаций"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR98Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r98', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr98', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Закрытие трудового семестра"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Закрытие трудового семестра"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR97Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r97', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr97', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Открытие трудового семестра"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Открытие трудового семестра"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR96Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r96', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr96', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Региональная школа подготовки командиров и комиссаров РСО"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Региональная школа подготовки командиров и комиссаров РСО"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR95Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r95', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr95', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "День РСО"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "День РСО"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR94Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r94', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr94', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Конкурс профессионального мастерства"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Конкурс профессионального мастерства"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR93Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r93', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr93', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Спартакиада студенческих отрядов и комплекс мероприятий РСО-спорт"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Спартакиада студенческих отрядов и комплекс мероприятий РСО-спорт"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR92Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r92', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr92', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Творческий фестиваль"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Творческий фестиваль"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR91Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r91', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr91', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Снежный десант РСО"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Снежный десант РСО"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR911Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r911', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr911', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Алгоритмы роста"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Алгоритмы роста"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR910Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r910', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr910', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Всероссийская акция «Вожатский диктант»"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Всероссийская акция «Вожатский диктант»"',
            },
        ),
    ]
