# Generated by Django 4.2.7 on 2024-07-20 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regional_competitions', '0003_alter_regionalr4event_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.PositiveSmallIntegerField(verbose_name='Номер показателя')),
                ('report_id', models.PositiveSmallIntegerField(verbose_name='Айди показателя')),
                ('changes', models.JSONField(verbose_name='Изменения эксперта окружного штаба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменений')),
                ('central_headquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.centralheadquarter', verbose_name='Верифицирующий ЦШ')),
                ('district_headquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.districtheadquarter', verbose_name='Верифицирующий ОШ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Верифицирующее лицо')),
            ],
            options={
                'verbose_name': 'Изменения ОШ и ЦШ отчета РШ',
                'verbose_name_plural': 'Изменения ОШ и ЦШ отчетов РШ',
            },
        ),
        migrations.CreateModel(
            name='CHqRejectingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.PositiveSmallIntegerField(verbose_name='Номер показателя')),
                ('report_id', models.PositiveSmallIntegerField(verbose_name='Айди показателя')),
                ('reasons', models.JSONField(verbose_name='Причины отклонений тех или иных полей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменений')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отклонившее лицо')),
            ],
            options={
                'verbose_name': 'Причины отклонений ЦШ по отчету',
                'verbose_name_plural': 'Причины отклонений ЦШ по отчетам',
            },
        ),
    ]
