# Generated by Django 4.2.7 on 2024-08-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0004_regionalr13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr101link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на социальные сети/электронные СМИ, подтверждающие проведение акции'),
        ),
        migrations.AlterField(
            model_name='regionalr102link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на социальные сети/электронные СМИ, подтверждающие проведение акции'),
        ),
        migrations.AlterField(
            model_name='regionalr16',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Наличие трудового проекта, в котором ЛО РСО одержал победу'),
        ),
        migrations.AlterField(
            model_name='regionalr16link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на группу проекта в социальных сетях'),
        ),
        migrations.AlterField(
            model_name='regionalr16project',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование проекта, в котором ЛСО РО одержал победу'),
        ),
        migrations.AlterField(
            model_name='regionalr16project',
            name='project_scale',
            field=models.CharField(blank=True, choices=[('Всероссийский', 'Всероссийский'), ('Окружной', 'Окружной'), ('Межрегиональный', 'Межрегиональный')], max_length=30, null=True, verbose_name='Масштаб проекта'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Общее количество участников'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='ro_participants_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество человек из своего региона, принявших участие в трудовом проекте'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала проведения мероприятия'),
        ),
        migrations.CreateModel(
            name='RegionalR14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('report_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_14', to='regional_competitions.regionalr12', verbose_name='Отчет 12')),
                ('report_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_14', to='regional_competitions.regionalr13', verbose_name='Отчет 13')),
            ],
            options={
                'verbose_name': 'Отчет по 14 показателю',
                'verbose_name_plural': 'Отчеты по 14 показателю',
            },
        ),
    ]
