# Generated by Django 4.2.7 on 2024-07-21 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regional_competitions', '0004_rverificationlog_chqrejectinglog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rverificationlog',
            options={'verbose_name': 'Логи изменений отчета РШ', 'verbose_name_plural': 'Логи изменений отчетов РШ'},
        ),
        migrations.RemoveField(
            model_name='rverificationlog',
            name='changes',
        ),
        migrations.AddField(
            model_name='rverificationlog',
            name='data',
            field=models.JSONField(default=1, verbose_name='Изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rverificationlog',
            name='is_central_data',
            field=models.BooleanField(default=False, verbose_name='Данные ЦШ'),
        ),
        migrations.AddField(
            model_name='rverificationlog',
            name='is_district_data',
            field=models.BooleanField(default=False, verbose_name='Данные ОШ'),
        ),
        migrations.AddField(
            model_name='rverificationlog',
            name='is_regional_data',
            field=models.BooleanField(default=False, verbose_name='Данные РШ'),
        ),
        migrations.AddField(
            model_name='rverificationlog',
            name='regional_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_verification_logs', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб'),
        ),
        migrations.AlterField(
            model_name='rverificationlog',
            name='central_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_verification_logs', to='headquarters.centralheadquarter', verbose_name='Верифицирующий ЦШ'),
        ),
        migrations.AlterField(
            model_name='rverificationlog',
            name='district_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_verification_logs', to='headquarters.districtheadquarter', verbose_name='Верифицирующий ОШ'),
        ),
        migrations.AlterField(
            model_name='rverificationlog',
            name='report_id',
            field=models.PositiveSmallIntegerField(verbose_name='ID отчета'),
        ),
        migrations.AlterField(
            model_name='rverificationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_verification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Верифицирующее лицо'),
        ),
    ]
