# Generated by Django 4.2.7 on 2024-08-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regional_competitions", "0004_regionalr13"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalR14",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "report_12",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_14",
                        to="regional_competitions.regionalr12",
                        verbose_name="Отчет 12",
                    ),
                ),
                (
                    "report_13",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_14",
                        to="regional_competitions.regionalr13",
                        verbose_name="Отчет 13",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 14 показателю",
                "verbose_name_plural": "Отчеты по 14 показателю",
            },
        ),
    ]
