# Generated by Django 4.2.7 on 2024-08-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0005_alter_regionalr101link_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr4link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='regionalr5link',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='URL-адрес'),
        ),
    ]
