# Generated by Django 4.2.7 on 2024-08-20 16:57

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions.utils


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0035_alter_area_name_alter_centralheadquarter_name_and_more"),
        (
            "regional_competitions",
            "0005_regionalr71_regionalr710_regionalr710link_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalR18",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 18 показателю",
                "verbose_name_plural": "Отчеты по 18 показателю",
            },
        ),
        migrations.CreateModel(
            name="RegionalR18Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=regional_competitions.utils.regional_comp_regulations_files_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "regional_r18",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="regional_competitions.regionalr18",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект по 18 показателю",
                "verbose_name_plural": "Проекты по 18 показателю",
            },
        ),
        migrations.CreateModel(
            name="RegionalR18Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка на публикацию")),
                (
                    "regional_r18_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr18project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка по 18 показателю",
                "verbose_name_plural": "Ссылки по 18 показателю",
            },
        ),
    ]
