# Generated by Django 4.2.7 on 2024-07-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('regional_competitions', '0005_alter_rverificationlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 7 показателю',
                'verbose_name_plural': 'Отчеты по 7 показателю',
            },
        ),
        migrations.AlterField(
            model_name='chqrejectinglog',
            name='reasons',
            field=models.JSONField(verbose_name='Причины отклонения'),
        ),
        migrations.CreateModel(
            name='RegionalR7Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Призовое место')),
                ('regional_r7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='regional_competitions.regionalr7', verbose_name='Отчет')),
            ],
        ),
    ]
