# Generated by Django 4.2.7 on 2024-08-20 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0036_regionalheadquarteremail"),
        (
            "regional_competitions",
            "0006_regionalr18_regionalr18project_regionalr18link",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseRegionalR6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, verbose_name="Отправлен на верификацию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "verified_by_chq",
                    models.BooleanField(null=True, verbose_name="Верифицирован ЦШ"),
                ),
                (
                    "verified_by_dhq",
                    models.BooleanField(default=False, verbose_name="Верифицирован ОШ"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "number_of_members",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество человек принявших участие",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegionalR61",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПрО «Арктика»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПрО «Арктика»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR610",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПО «Артек»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПО «Артек»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR611",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПО «Дельфин.ru»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПО «Дельфин.ru»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR612",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПО «Гагарин»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПО «Гагарин»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR613",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПО «Океан»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПО «Океан»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR614",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПО «Орлёнок»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПО «Орлёнок»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR615",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПО «Сириус»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПО «Сириус»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR616",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСССхО «Агроном-сад»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСССхО «Агроном-сад»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR617",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR618",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВССПуО «Край Света»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВССПуО «Край Света»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR619",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСССервО «Мрия»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСССервО «Мрия»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR62",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСПрО «КАМАЗ»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСПрО «КАМАЗ»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR620",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСССервО «Метрополь»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСССервО «Метрополь»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR621",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСССервО «Сочи Парк Отель»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСССервО «Сочи Парк Отель»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR622",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСССервО «Взлетная полоса»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСССервО «Взлетная полоса»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR623",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Атлант»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Атлант»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR624",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Академия»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Академия»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR625",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Аметист»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Аметист»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR626",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Сердце Пармы»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Сердце Пармы»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR627",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Белогорье»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Белогорье»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR628",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Коллеги»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Коллеги»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR629",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Призвание»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Призвание»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR63",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Мирный атом»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Мирный атом»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR630",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Клиника»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Клиника»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR631",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСФО «36,6»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСФО «36,6»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR632",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСМО «Галиотис»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСМО «Галиотис»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR633",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСОП Екатеринбург"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСОП Екатеринбург"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR634",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСОП Нижний Новгород"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСОП Нижний Новгород"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR635",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСОП Москва"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСОП Москва"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR636",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСОП Санкт-Петербург"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСОП Санкт-Петербург"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR64",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Мирный атом-ПРОРЫВ»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Мирный атом-ПРОРЫВ»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR65",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Мирный атом-ЛАЭС»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Мирный атом-ЛАЭС»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR66",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «СКИФ»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «СКИФ»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR67",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Север»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Север»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR68",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Сибирь»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Сибирь»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR69",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «БАМ 2.0»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «БАМ 2.0»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR69Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r69",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr69",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «БАМ 2.0»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «БАМ 2.0»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR68Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r68",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr68",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Сибирь»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Сибирь»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR67Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r67",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr67",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Север»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Север»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR66Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r66",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr66",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «СКИФ»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «СКИФ»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR65Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r65",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr65",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Мирный атом-ЛАЭС»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Мирный атом-ЛАЭС»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR64Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r64",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr64",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Мирный атом-ПРОРЫВ»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Мирный атом-ПРОРЫВ»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR63Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r63",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr63",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Мирный атом»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Мирный атом»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR636Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r636",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr636",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСОП Санкт-Петербург"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСОП Санкт-Петербург"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR635Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r635",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr635",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСОП Москва"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСОП Москва"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR634Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r634",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr634",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСОП Нижний Новгород"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСОП Нижний Новгород"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR633Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r633",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr633",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСОП Екатеринбург"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСОП Екатеринбург"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR632Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r632",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr632",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Галиотис»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Галиотис»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR631Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r631",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr631",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСФО «36,6»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСФО «36,6»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR630Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r630",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr630",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Клиника»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Клиника»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR62Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r62",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr62",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПрО «КАМАЗ»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПрО «КАМАЗ»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR629Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r629",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr629",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Призвание»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Призвание»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR628Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r628",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr628",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Коллеги»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Коллеги»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR627Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r627",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr627",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Белогорье»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Белогорье»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR626Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r626",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr626",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Сердце Пармы»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Сердце Пармы»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR625Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r625",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr625",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Аметист»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Аметист»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR624Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r624",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr624",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Академия»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Академия»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR623Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r623",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr623",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСМО «Атлант»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСМО «Атлант»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR622Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r622",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr622",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСССервО «Взлетная полоса»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСССервО «Взлетная полоса»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR621Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r621",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr621",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСССервО «Сочи Парк Отель»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСССервО «Сочи Парк Отель»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR620Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r620",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr620",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСССервО «Метрополь»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСССервО «Метрополь»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR61Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r61",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr61",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПрО «Арктика»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПрО «Арктика»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR619Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r619",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr619",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСССервО «Мрия»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСССервО «Мрия»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR618Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r618",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr618",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВССПуО «Край Света»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВССПуО «Край Света»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR617Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r617",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr617",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR616Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r616",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr616",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСССхО «Агроном-сад»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСССхО «Агроном-сад»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR615Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r615",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr615",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПО «Сириус»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПО «Сириус»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR614Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r614",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr614",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПО «Орлёнок»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПО «Орлёнок»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR613Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r613",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr613",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПО «Океан»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПО «Океан»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR612Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r612",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr612",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПО «Гагарин»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПО «Гагарин»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR611Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r611",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr611",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПО «Дельфин.ru»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПО «Дельфин.ru»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR610Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r610",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr610",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСПО «Артек»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСПО «Артек»"',
            },
        ),
    ]
