# Generated by Django 4.2.7 on 2024-07-23 04:17

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('regional_competitions', '0006_regionalr7_alter_chqrejectinglog_reasons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_project', models.BooleanField(verbose_name='Наличие трудового проекта, в котором ЛО РСО одержал победу')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 16 показателю',
                'verbose_name_plural': 'Отчеты по 16 показателям',
            },
        ),
        migrations.AlterModelOptions(
            name='regionalr7place',
            options={'verbose_name': 'Призовое место по 7 показателю', 'verbose_name_plural': 'Призовые места по 7 показателю'},
        ),
        migrations.CreateModel(
            name='RegionalR16Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование проекта, в котором ЛСО РО одержал победу')),
                ('project_scale', models.CharField(choices=[('Всероссийский', 'Всероссийский'), ('Окружной', 'Окружной'), ('Межрегиональный', 'Межрегиональный')], max_length=30, verbose_name='Масштаб проекта')),
                ('regulations', models.FileField(upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Положение о проекте')),
                ('regional_r16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='regional_competitions.regionalr16', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Проект по 16 показателю',
                'verbose_name_plural': 'Проекты по 16 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR16Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на группу проекта в социальных сетях')),
                ('regional_r16_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr16project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ссылка по 16 показателю',
                'verbose_name_plural': 'Ссылки по 16 показателю',
            },
        ),
    ]
