# Generated by Django 4.2.7 on 2024-07-23 04:22

from django.db import migrations, models
import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0007_regionalr16_alter_regionalr7place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr16project',
            name='regulations',
            field=models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Положение о проекте'),
        ),
    ]
