# Generated by Django 4.2.7 on 2024-08-30 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0036_regionalheadquarteremail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regional_competitions", "0008_remove_regionalr71_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticalregionalreport",
            name="employed_ro_rso",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Количество работников штабов РО РСО",
            ),
        ),
        migrations.AddField(
            model_name="statisticalregionalreport",
            name="employed_so_oovo",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Количество работников штабов СО ООВО",
            ),
        ),
        migrations.AddField(
            model_name="statisticalregionalreport",
            name="employed_so_poo",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Количество работников штабов СО ПОО",
            ),
        ),
        migrations.CreateModel(
            name="ExpertRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "central_headquarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.centralheadquarter",
                        verbose_name="Центральный штаб",
                    ),
                ),
                (
                    "district_headquarter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.districtheadquarter",
                        verbose_name="Районный штаб",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль эксперта",
                "verbose_name_plural": "Роли экспертов",
            },
        ),
        migrations.CreateModel(
            name="AdditionalStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("value", models.PositiveIntegerField(verbose_name="Значение")),
                (
                    "statistical_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_statistics",
                        to="regional_competitions.statisticalregionalreport",
                        verbose_name="Статистический отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свои варианты - статистический отчет",
                "verbose_name_plural": "Свои варианты - статистические отчеты",
            },
        ),
        migrations.AddConstraint(
            model_name="expertrole",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("central_headquarter__isnull", False),
                    ("district_headquarter__isnull", False),
                    _connector="OR",
                ),
                name="at_least_one_headquarter",
            ),
        ),
        migrations.AddConstraint(
            model_name="expertrole",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("central_headquarter__isnull", False),
                    ("district_headquarter__isnull", False),
                    _negated=True,
                ),
                name="not_both_headquarters",
            ),
        ),
    ]
