# Generated by Django 4.2.7 on 2024-08-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0008_remove_regionalr71_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='employed_ro_rso',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество работников штабов РО РСО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='employed_so_oovo',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество работников штабов СО ООВО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='employed_so_poo',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество работников штабов СО ПОО'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdditionalStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.PositiveIntegerField(verbose_name='Значение')),
                ('statistical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_statistics', to='regional_competitions.statisticalregionalreport', verbose_name='Статистический отчет')),
            ],
            options={
                'verbose_name': 'Свои варианты - статистический отчет',
                'verbose_name_plural': 'Свои варианты - статистические отчеты',
            },
        ),
    ]
