# Generated by Django 4.2.7 on 2024-07-23 13:59

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('regional_competitions', '0008_alter_regionalr16project_regulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение акции')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 10 показателю - "Снежный Десант"',
                'verbose_name_plural': 'Отчеты по 10 показателю - "Снежный Десант',
            },
        ),
        migrations.CreateModel(
            name='RegionalR102',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение акции')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 10 показателю - "Поклонимся Великим годам"',
                'verbose_name_plural': 'Отчеты по 10 показателю - "Поклонимся Великим годам"',
            },
        ),
        migrations.AlterModelOptions(
            name='regionalr16',
            options={'verbose_name': 'Отчет по 16 показателю', 'verbose_name_plural': 'Отчеты по 16 показателю'},
        ),
        migrations.AlterModelOptions(
            name='regionalr7place',
            options={'verbose_name': 'Данные по призовому месту по 7 показателю', 'verbose_name_plural': 'Данные по призовым местам по 7 показателю'},
        ),
        migrations.CreateModel(
            name='RegionalR102Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на социальные сети/электронные СМИ, подтверждающие проведение акции')),
                ('regional_r102', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr102', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 10 показателю - "Поклонимся Великим годам"',
                'verbose_name_plural': 'Ссылки по 10 показателю - "Поклонимся Великим годам',
            },
        ),
        migrations.CreateModel(
            name='RegionalR101Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на социальные сети/электронные СМИ, подтверждающие проведение акции')),
                ('regional_r101', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr101', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 10 показателю - "Снежный Десант"',
                'verbose_name_plural': 'Ссылки по 10 показателю - "Снежный Десант"',
            },
        ),
    ]
