# Generated by Django 4.2.7 on 2024-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0009_regionalr101_regionalr102_alter_regionalr16_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticalregionalreport',
            name='employed_oop',
        ),
        migrations.RemoveField(
            model_name='statisticalregionalreport',
            name='employed_sses',
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='employed_sop',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество трудоустроенных СОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='employed_ssho',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество трудоустроенных ССхО'),
            preserve_default=False,
        ),
    ]
