# Generated by Django 4.2.7 on 2024-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0009_statisticalregionalreport_employed_ro_rso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticalregionalreport',
            name='employed_ro_rso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов РО РСО'),
        ),
        migrations.AlterField(
            model_name='statisticalregionalreport',
            name='employed_so_oovo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов СО ООВО'),
        ),
        migrations.AlterField(
            model_name='statisticalregionalreport',
            name='employed_so_poo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов СО ПОО'),
        ),
    ]
