# Generated by Django 4.2.7 on 2024-08-31 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0010_regionalr2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalr17',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='regionalr17',
            name='score',
        ),
        migrations.RemoveField(
            model_name='regionalr17',
            name='verified_by_chq',
        ),
        migrations.RemoveField(
            model_name='regionalr17',
            name='verified_by_dhq',
        ),
        migrations.RemoveField(
            model_name='regionalr19',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='regionalr19',
            name='score',
        ),
        migrations.RemoveField(
            model_name='regionalr19',
            name='verified_by_chq',
        ),
        migrations.RemoveField(
            model_name='regionalr19',
            name='verified_by_dhq',
        ),
        migrations.AlterField(
            model_name='expertrole',
            name='central_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_experts', to='headquarters.centralheadquarter', verbose_name='Центральный штаб'),
        ),
        migrations.AlterField(
            model_name='expertrole',
            name='district_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_experts', to='headquarters.districtheadquarter', verbose_name='Окружной штаб'),
        ),
        migrations.AlterField(
            model_name='expertrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regional_expert', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
