# Generated by Django 4.2.7 on 2024-09-10 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0012_regionalr637_regionalr638_regionalr639_regionalr640_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('amount_of_membership_fees_2023', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 1 показателю',
                'verbose_name_plural': 'Отчеты по 1 показателю',
            },
        ),
    ]
