# Generated by Django 4.2.7 on 2024-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regional_competitions", "0013_regionalr3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regionalr3",
            options={
                "verbose_name": "Отчет по 3 показателю",
                "verbose_name_plural": "Отчеты по 3 показателю",
            },
        ),
        migrations.AlterField(
            model_name="regionalr18link",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на публикацию"
            ),
        ),
    ]
