# Generated by Django 4.2.7 on 2024-09-30 15:35

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0014_alter_regionalr3_options_alter_regionalr18link_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR691',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВСФО «36,6»"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВСФО «36,6»"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR692',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВСМО «Галиотис»"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Галиотис»"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR693',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВСОП Екатеринбург"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВСОП Екатеринбург"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR694',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВСОП Нижний Новгород"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВСОП Нижний Новгород"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR695',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВСОП Москва"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВСОП Москва"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR696',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВСОП Санкт-Петербург"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВСОП Санкт-Петербург"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR697',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "ВПТОП «АлабугаТОП»"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "ВПТОП «АлабугаТОП»"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR745',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('prize_place', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Призовое место')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions.utils.regional_comp_regulations_files_path, verbose_name='Скан подтверждающего документа')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 7 показателю - "ВПТОП «АлабугаТОП»"',
                'verbose_name_plural': 'Отчеты по 7 показателю - "ВПТОП «АлабугаТОП»"',
            },
        ),
        migrations.AlterModelOptions(
            name='regionalr652',
            options={'verbose_name': 'Отчет по 6 показателю - "Всероссийский слет студенческих медицинских отрядов «Всегда 20»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "Всероссийский слет студенческих медицинских отрядов «Всегда 20»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr652link',
            options={'verbose_name': 'Ссылка по 6 показателю - "Всероссийский слет студенческих медицинских отрядов «Всегда 20»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "Всероссийский слет студенческих медицинских отрядов «Всегда 20»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr653',
            options={'verbose_name': 'Отчет по 6 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"', 'verbose_name_plural': 'Отчеты по 6 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr653link',
            options={'verbose_name': 'Ссылка по 6 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"', 'verbose_name_plural': 'Ссылки по 6 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr654',
            options={'verbose_name': 'Отчет по 6 показателю - "Цифровой прорыв. Сезон: Искусственный интеллект"', 'verbose_name_plural': 'Отчеты по 6 показателю - "Цифровой прорыв. Сезон: Искусственный интеллект"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr654link',
            options={'verbose_name': 'Ссылка по 6 показателю - "Цифровой прорыв. Сезон: Искусственный интеллект"', 'verbose_name_plural': 'Ссылки по 6 показателю - "Цифровой прорыв. Сезон: Искусственный интеллект"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr655',
            options={'verbose_name': 'Отчет по 6 показателю - "IV Международный строительный чемпионат"', 'verbose_name_plural': 'Отчеты по 6 показателю - "IV Международный строительный чемпионат"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr655link',
            options={'verbose_name': 'Ссылка по 6 показателю - "IV Международный строительный чемпионат"', 'verbose_name_plural': 'Ссылки по 6 показателю - "IV Международный строительный чемпионат"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr656',
            options={'verbose_name': 'Отчет по 6 показателю - "Слёт студенческих отрядов ПАО «Газпром»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "Слёт студенческих отрядов ПАО «Газпром»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr656link',
            options={'verbose_name': 'Ссылка по 6 показателю - "Слёт студенческих отрядов ПАО «Газпром»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "Слёт студенческих отрядов ПАО «Газпром»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr657',
            options={'verbose_name': 'Отчет по 6 показателю - "Всероссийский форум студенческих педагогических отрядов"', 'verbose_name_plural': 'Отчеты по 6 показателю - "Всероссийский форум студенческих педагогических отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr657link',
            options={'verbose_name': 'Ссылка по 6 показателю - "Всероссийский форум студенческих педагогических отрядов"', 'verbose_name_plural': 'Ссылки по 6 показателю - "Всероссийский форум студенческих педагогических отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr658',
            options={'verbose_name': 'Отчет по 6 показателю - "Всероссийская научная конференция студенческих отрядов, посвященная 65-летию движения студенческих отрядов"', 'verbose_name_plural': 'Отчеты по 6 показателю - "Всероссийская научная конференция студенческих отрядов, посвященная 65-летию движения студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr658link',
            options={'verbose_name': 'Ссылка по 6 показателю - "Всероссийская научная конференция студенческих отрядов, посвященная 65-летию движения студенческих отрядов"', 'verbose_name_plural': 'Ссылки по 6 показателю - "Всероссийская научная конференция студенческих отрядов, посвященная 65-летию движения студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr659',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПрО «Арктика»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПрО «Арктика»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr659link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПрО «Арктика»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПрО «Арктика»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr660',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПрО «КАМАЗ»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПрО «КАМАЗ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr660link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПрО «КАМАЗ»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПрО «КАМАЗ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr661',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПрО «Алабуга – Композит»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПрО «Алабуга – Композит»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr661link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПрО «Алабуга – Композит»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПрО «Алабуга – Композит»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr662',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «Мирный атом»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «Мирный атом»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr662link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «Мирный атом»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «Мирный атом»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr663',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «Мирный атом – ПРОРЫВ»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «Мирный атом – ПРОРЫВ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr663link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «Мирный атом – ПРОРЫВ»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «Мирный атом – ПРОРЫВ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr664',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «Мирный атом – ЛАЭС»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «Мирный атом – ЛАЭС»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr664link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «Мирный атом – ЛАЭС»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «Мирный атом – ЛАЭС»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr665',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «СКИФ»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «СКИФ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr665link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «СКИФ»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «СКИФ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr666',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «Север»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «Север»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr666link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «Север»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «Север»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr667',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «Сибирь»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «Сибирь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr667link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «Сибирь»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «Сибирь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr668',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСС «БАМ 2.0»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСС «БАМ 2.0»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr668link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСС «БАМ 2.0»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСС «БАМ 2.0»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr669',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПО «Артек»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПО «Артек»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr669link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПО «Артек»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПО «Артек»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr670',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПО «Дельфин.ru»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПО «Дельфин.ru»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr670link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПО «Дельфин.ru»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПО «Дельфин.ru»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr671',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПО «Гагарин»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПО «Гагарин»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr671link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПО «Гагарин»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПО «Гагарин»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr672',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПО «Океан»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПО «Океан»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr672link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПО «Океан»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПО «Океан»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr673',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПО «Орлёнок»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПО «Орлёнок»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr673link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПО «Орлёнок»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПО «Орлёнок»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr674',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСПО «Сириус»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСПО «Сириус»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr674link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСПО «Сириус»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСПО «Сириус»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr675',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСССхО «Агроном-сад»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСССхО «Агроном-сад»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr675link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСССхО «Агроном-сад»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСССхО «Агроном-сад»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr676',
            options={'verbose_name': 'Отчет по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr676link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВССхО «МоСт» (Молочный стандарт)"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr677',
            options={'verbose_name': 'Отчет по 6 показателю - "ВССПуО «Край Света»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВССПуО «Край Света»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr677link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВССПуО «Край Света»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВССПуО «Край Света»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr678',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСССервО «Мрия»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСССервО «Мрия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr678link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСССервО «Мрия»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСССервО «Мрия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr679',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСССервО «Метрополь»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСССервО «Метрополь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr679link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСССервО «Метрополь»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСССервО «Метрополь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr680',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСССервО «Сочи Парк Отель»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСССервО «Сочи Парк Отель»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr680link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСССервО «Сочи Парк Отель»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСССервО «Сочи Парк Отель»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr681',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСССервО «Взлетная полоса»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСССервО «Взлетная полоса»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr681link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСССервО «Взлетная полоса»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСССервО «Взлетная полоса»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr682',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСССервО «Первый рассвет»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСССервО «Первый рассвет»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr682link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСССервО «Первый рассвет»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСССервО «Первый рассвет»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr683',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Атлант»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Атлант»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr683link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Атлант»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Атлант»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr684',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Академия»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Академия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr684link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Академия»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Академия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr685',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Аметист»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Аметист»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr685link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Аметист»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Аметист»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr686',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Сердце Пармы»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Сердце Пармы»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr686link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Сердце Пармы»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Сердце Пармы»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr687',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Белогорье»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Белогорье»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr687link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Белогорье»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Белогорье»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr688',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Коллеги»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Коллеги»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr688link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Коллеги»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Коллеги»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr689',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Призвание»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Призвание»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr689link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Призвание»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Призвание»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr690',
            options={'verbose_name': 'Отчет по 6 показателю - "ВСМО «Клиника»"', 'verbose_name_plural': 'Отчеты по 6 показателю - "ВСМО «Клиника»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr690link',
            options={'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Клиника»"', 'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Клиника»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr711',
            options={'verbose_name': 'Отчет по 7 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"', 'verbose_name_plural': 'Отчеты по 7 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr711link',
            options={'verbose_name': 'Ссылка по 7 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"', 'verbose_name_plural': 'Ссылки по 7 показателю - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr712',
            options={'verbose_name': 'Отчет по 7 показателю - "Всероссийский форум студенческих педагогических отрядов"', 'verbose_name_plural': 'Отчеты по 7 показателю - "Всероссийский форум студенческих педагогических отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr712link',
            options={'verbose_name': 'Ссылка по 7 показателю - "Всероссийский форум студенческих педагогических отрядов"', 'verbose_name_plural': 'Ссылки по 7 показателю - "Всероссийский форум студенческих педагогических отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr713',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСПрО «Арктика»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСПрО «Арктика»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr713link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСПрО «Арктика»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСПрО «Арктика»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr714',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСПрО «КАМАЗ»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСПрО «КАМАЗ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr714link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСПрО «КАМАЗ»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСПрО «КАМАЗ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr715',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСПрО «Алабуга – Композит»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСПрО «Алабуга – Композит»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr715link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСПрО «Алабуга – Композит»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСПрО «Алабуга – Композит»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr716',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «Мирный атом»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «Мирный атом»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr716link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «Мирный атом»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «Мирный атом»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr717',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «Мирный атом – ПРОРЫВ»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «Мирный атом – ПРОРЫВ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr717link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «Мирный атом – ПРОРЫВ»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «Мирный атом – ПРОРЫВ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr718',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «Мирный атом – ЛАЭС»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «Мирный атом – ЛАЭС»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr718link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «Мирный атом – ЛАЭС»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «Мирный атом – ЛАЭС»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr719',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «СКИФ»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «СКИФ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr719link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «СКИФ»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «СКИФ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr720',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «Север»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «Север»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr720link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «Север»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «Север»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr721',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «Сибирь»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «Сибирь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr721link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «Сибирь»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «Сибирь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr722',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСС «БАМ 2.0»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСС «БАМ 2.0»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr722link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСС «БАМ 2.0»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСС «БАМ 2.0»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr723',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСПО «Дельфин.ru»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСПО «Дельфин.ru»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr723link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСПО «Дельфин.ru»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСПО «Дельфин.ru»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr724',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСССхО «Агроном-сад»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСССхО «Агроном-сад»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr724link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСССхО «Агроном-сад»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСССхО «Агроном-сад»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr725',
            options={'verbose_name': 'Отчет по 7 показателю - "ВССПуО «Край Света»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВССПуО «Край Света»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr725link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВССПуО «Край Света»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВССПуО «Край Света»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr726',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСССервО «Мрия»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСССервО «Мрия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr726link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСССервО «Мрия»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСССервО «Мрия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr727',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСССервО «Метрополь»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСССервО «Метрополь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr727link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСССервО «Метрополь»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСССервО «Метрополь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr728',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСССервО «Сочи Парк Отель»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСССервО «Сочи Парк Отель»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr728link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСССервО «Сочи Парк Отель»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСССервО «Сочи Парк Отель»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr729',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСССервО «Взлетная полоса»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСССервО «Взлетная полоса»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr729link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСССервО «Взлетная полоса»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСССервО «Взлетная полоса»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr730',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСССервО «Первый рассвет»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСССервО «Первый рассвет»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr730link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСССервО «Первый рассвет»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСССервО «Первый рассвет»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr731',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Атлант»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Атлант»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr731link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Атлант»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Атлант»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr732',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Академия»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Академия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr732link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Академия»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Академия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr733',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Аметист»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Аметист»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr733link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Аметист»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Аметист»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr734',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Сердце Пармы»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Сердце Пармы»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr734link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Сердце Пармы»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Сердце Пармы»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr735',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Белогорье»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Белогорье»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr735link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Белогорье»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Белогорье»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr736',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Коллеги»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Коллеги»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr736link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Коллеги»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Коллеги»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr737',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Призвание»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Призвание»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr737link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Призвание»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Призвание»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr738',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Клиника»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Клиника»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr738link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Клиника»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Клиника»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr739',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСФО «36,6»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСФО «36,6»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr739link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСФО «36,6»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСФО «36,6»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr740',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСМО «Галиотис»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСМО «Галиотис»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr740link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСМО «Галиотис»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСМО «Галиотис»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr741',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСОП Екатеринбург"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСОП Екатеринбург"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr741link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСОП Екатеринбург"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСОП Екатеринбург"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr742',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСОП Нижний Новгород"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСОП Нижний Новгород"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr742link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСОП Нижний Новгород"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСОП Нижний Новгород"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr743',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСОП Москва"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСОП Москва"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr743link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСОП Москва"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСОП Москва"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr744',
            options={'verbose_name': 'Отчет по 7 показателю - "ВСОП Санкт-Петербург"', 'verbose_name_plural': 'Отчеты по 7 показателю - "ВСОП Санкт-Петербург"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr744link',
            options={'verbose_name': 'Ссылка по 7 показателю - "ВСОП Санкт-Петербург"', 'verbose_name_plural': 'Ссылки по 7 показателю - "ВСОП Санкт-Петербург"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr75',
            options={'verbose_name': 'Отчет по 7 показателю - "Всероссийская профориентационная смена  «Труд крут»"', 'verbose_name_plural': 'Отчеты по 7 показателю - "Всероссийская профориентационная смена  «Труд крут»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr75link',
            options={'verbose_name': 'Ссылка по 7 показателю - "Всероссийская профориентационная смена  «Труд крут»"', 'verbose_name_plural': 'Ссылки по 7 показателю - "Всероссийская профориентационная смена  «Труд крут»"'},
        ),
        migrations.CreateModel(
            name='RegionalR745Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r745', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr745', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 7 показателю - "ВПТОП «АлабугаТОП»"',
                'verbose_name_plural': 'Ссылки по 7 показателю - "ВПТОП «АлабугаТОП»"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR697Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r697', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr697', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВПТОП «АлабугаТОП»"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВПТОП «АлабугаТОП»"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR696Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r696', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr696', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВСОП Санкт-Петербург"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВСОП Санкт-Петербург"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR695Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r695', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr695', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВСОП Москва"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВСОП Москва"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR694Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r694', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr694', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВСОП Нижний Новгород"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВСОП Нижний Новгород"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR693Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r693', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr693', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВСОП Екатеринбург"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВСОП Екатеринбург"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR692Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r692', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr692', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВСМО «Галиотис»"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВСМО «Галиотис»"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR691Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r691', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr691', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "ВСФО «36,6»"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "ВСФО «36,6»"',
            },
        ),
    ]
