# Generated by Django 4.2.7 on 2024-09-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0014_alter_regionalr3_options_alter_regionalr18link_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 1 показателю')),
                ('r2_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 2 показателю')),
                ('r3_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 3 показателю')),
                ('r4_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 4 показателю')),
                ('r5_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 5 показателю')),
                ('r6_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 6 показателю')),
                ('r7_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 7 показателю')),
                ('r8_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 8 показателю')),
                ('r9_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 9 показателю')),
                ('r10_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 10 показателю')),
                ('r11_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 11 показателю')),
                ('r12_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 12 показателю')),
                ('r13_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 13 показателю')),
                ('r14_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 14 показателю')),
                ('r15_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 15 показателю')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_competitions_rankings', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Место участника по показателю',
                'verbose_name_plural': 'Места участников по показателям',
            },
        ),
    ]
