# Generated by Django 4.2.7 on 2024-09-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0036_regionalheadquarteremail"),
        ("regional_competitions", "0015_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalr14",
            name="regional_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="headquarters.regionalheadquarter",
                verbose_name="Региональный штаб",
            ),
        ),
    ]
