# Generated by Django 4.2.7 on 2024-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0015_regionalr691_regionalr692_regionalr693_regionalr694_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseregionalr6',
            name='number_of_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество человек принявших участие'),
        ),
        migrations.AlterField(
            model_name='regionalr13',
            name='number_of_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество членов РО РСО, принявших участие'),
        ),
        migrations.AlterField(
            model_name='regionalr19',
            name='employed_student_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество трудоустроенных в штат принимающей организации по итогам третьего трудового семестра'),
        ),
        migrations.AlterField(
            model_name='regionalr19',
            name='employed_student_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество трудоустроенных студентов в третий трудовой семестр'),
        ),
        migrations.AlterField(
            model_name='regionalr4event',
            name='participants_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='regionalr5event',
            name='participants_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Общее количество участников'),
        ),
    ]
