# Generated by Django 4.2.7 on 2024-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0015_regionalr691_regionalr692_regionalr693_regionalr694_and_more'),
        ('regional_competitions', '0016_regionalr14_regional_headquarter'),
    ]

    operations = [
    ]
