# Generated by Django 4.2.7 on 2024-10-05 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0016_alter_baseregionalr6_number_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr2',
            name='full_time_students',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество студентов очной формы обучения'),
        ),
        migrations.AlterField(
            model_name='regionalr3',
            name='amount_of_membership_fees_2023',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
