# Generated by Django 4.2.7 on 2024-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0017_merge_20240930_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalr2',
            name='is_sent',
        ),
    ]
