# Generated by Django 4.2.7 on 2024-10-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0017_alter_regionalr2_full_time_students_and_more'),
        ('regional_competitions', '0018_remove_regionalr2_is_sent'),
    ]

    operations = [
    ]
