# Generated by Django 4.2.7 on 2024-10-09 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0019_merge_20241005_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalr102',
            options={'verbose_name': 'Отчет по 10 показателю - "Поклонимся великим тем годам"', 'verbose_name_plural': 'Отчеты по 10 показателю - "Поклонимся великим тем годам"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr102link',
            options={'verbose_name': 'Ссылка по 10 показателю - "Поклонимся великим тем годам"', 'verbose_name_plural': 'Ссылки по 10 показателю - "Поклонимся великим тем годам'},
        ),
        migrations.AlterModelOptions(
            name='regionalr911',
            options={'verbose_name': 'Отчет по 9 показателю - "Мероприятие по развитию направления ТОП в субъекте Российской Федерации"', 'verbose_name_plural': 'Отчеты по 9 показателю - "Мероприятие по развитию направления ТОП в субъекте Российской Федерации"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr911link',
            options={'verbose_name': 'Ссылка по 9 показателю - "Мероприятие по развитию направления ТОП в субъекте Российской Федерации"', 'verbose_name_plural': 'Ссылки по 9 показателю - "Мероприятие по развитию направления ТОП в субъекте Российской Федерации"'},
        ),
        migrations.AlterField(
            model_name='regionalr2',
            name='full_time_students',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество студентов очной формы обучения'),
        ),
    ]
