# Generated by Django 4.2.7 on 2024-10-06 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0019_merge_20241005_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr2',
            name='full_time_students',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество студентов очной формы обучения'),
        ),
    ]
