# Generated by Django 4.2.7 on 2024-10-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0020_alter_regionalr102_options_and_more'),
        ('regional_competitions', '0021_alter_regionalr61_options_alter_regionalr610_options_and_more'),
    ]

    operations = [
    ]
