# Generated by Django 4.2.7 on 2024-10-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0036_regionalheadquarteremail"),
        ("regional_competitions", "0022_merge_20241009_1926"),
    ]

    operations = [
        migrations.CreateModel(
            name="DumpStatisticalRegionalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participants_number",
                    models.PositiveIntegerField(
                        verbose_name="Количество членов регионального отделения"
                    ),
                ),
                (
                    "employed_sso",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных ССО"
                    ),
                ),
                (
                    "employed_spo",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных СПО"
                    ),
                ),
                (
                    "employed_sop",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных СОП"
                    ),
                ),
                (
                    "employed_smo",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных СМО"
                    ),
                ),
                (
                    "employed_sservo",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных ССервО"
                    ),
                ),
                (
                    "employed_ssho",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных ССхО"
                    ),
                ),
                (
                    "employed_specialized_detachments",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных, профильные отряды"
                    ),
                ),
                (
                    "employed_production_detachments",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных, производственные отряды"
                    ),
                ),
                (
                    "employed_top",
                    models.PositiveIntegerField(
                        verbose_name="Количество трудоустроенных, ТОП"
                    ),
                ),
                (
                    "employed_so_poo",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество работников штабов СО ПОО",
                    ),
                ),
                (
                    "employed_so_oovo",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество работников штабов СО ООВО",
                    ),
                ),
                (
                    "employed_ro_rso",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество работников штабов РО РСО",
                    ),
                ),
                (
                    "regional_headquarter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дамп статистического отчета РШ",
                "verbose_name_plural": "Дампы статистических отчетов РШ",
            },
        ),
    ]
