# Generated by Django 4.2.7 on 2024-10-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0023_dumpstatisticalregionalreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalr910link',
            name='regional_r910',
        ),
        migrations.AddField(
            model_name='regionalr4event',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование мероприятия'),
        ),
        migrations.AddField(
            model_name='regionalr5event',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование мероприятия'),
        ),
        migrations.DeleteModel(
            name='RegionalR910',
        ),
        migrations.DeleteModel(
            name='RegionalR910Link',
        ),
    ]
