# Generated by Django 4.2.7 on 2024-10-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0024_remove_regionalr910link_regional_r910_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR6100',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "Митап кураторов трудовых отрядов подростков «Будь в ТОПе!»"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "Митап кураторов трудовых отрядов подростков «Будь в ТОПе!»"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR698',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "Всероссийская патриотическая акция «Снежный десант РСО»"',
                'verbose_name_plural': 'Отчеты по 6 показателю - "Всероссийская патриотическая акция «Снежный десант РСО»"',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR699',
            fields=[
                ('baseregionalr6_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regional_competitions.baseregionalr6')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю - "Всероссийская патриотическая акция «Поклонимся великим тем годам» "',
                'verbose_name_plural': 'Отчеты по 6 показателю - "Всероссийская патриотическая акция «Поклонимся великим тем годам» "',
            },
            bases=('regional_competitions.baseregionalr6',),
        ),
        migrations.CreateModel(
            name='RegionalR699Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r699', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr699', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "Всероссийская патриотическая акция «Поклонимся великим тем годам» "',
                'verbose_name_plural': 'Ссылки по 6 показателю - "Всероссийская патриотическая акция «Поклонимся великим тем годам» "',
            },
        ),
        migrations.CreateModel(
            name='RegionalR698Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r698', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr698', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "Всероссийская патриотическая акция «Снежный десант РСО»"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "Всероссийская патриотическая акция «Снежный десант РСО»"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR6100Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r6100', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions.regionalr6100', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 6 показателю - "Митап кураторов трудовых отрядов подростков «Будь в ТОПе!»"',
                'verbose_name_plural': 'Ссылки по 6 показателю - "Митап кураторов трудовых отрядов подростков «Будь в ТОПе!»"',
            },
        ),
    ]
