# Generated by Django 4.2.7 on 2024-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0026_remove_regionalr710_regional_headquarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseregionalr6',
            name='is_project',
            field=models.BooleanField(default=False, verbose_name='Наличие'),
        ),
    ]
