# Generated by Django 4.2.7 on 2024-10-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regional_competitions", "0027_baseregionalr6_is_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalR6101",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "Всероссийский образовательный семинар в рамках Молодёжного форума «Алтай: Территория Развития»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "Всероссийский образовательный семинар в рамках Молодёжного форума «Алтай: Территория Развития»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6102",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "Праздничное мероприятие, приуроченное к 50-летию начала строительства Байкало-Амурской магистрали"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "Праздничное мероприятие, приуроченное к 50-летию начала строительства Байкало-Амурской магистрали"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6103",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "Всероссийский молодёжный форум «ОстроVа»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "Всероссийский молодёжный форум «ОстроVа»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6104",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "Всероссийский молодёжный форум «Машук», трек «Дружба»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "Всероссийский молодёжный форум «Машук», трек «Дружба»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6105",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "Всероссийская смена студенческих сельскохозяйственных отрядов в рамках Всероссийского форума «Ростов»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "Всероссийская смена студенческих сельскохозяйственных отрядов в рамках Всероссийского форума «Ростов»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6106",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "IV Международный строительный чемпионат"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "IV Международный строительный чемпионат"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6107",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "Петербургский международный газовый форум"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "Петербургский международный газовый форум"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6108",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "МССО «Босфор»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "МССО «Босфор»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6109",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "МССО «Дюна»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "МССО «Дюна»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6110",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "МССО «Лотос»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "МССО «Лотос»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6111",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "МССО «Тигр»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "МССО «Тигр»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6112",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "МССО «Пакш-2»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "МССО «Пакш-2»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6113",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВМС «Патриотический центр»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВМС «Патриотический центр»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6114",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Мирный атом (зимний этап)»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Мирный атом (зимний этап)»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6115",
            fields=[
                (
                    "baseregionalr6_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="regional_competitions.baseregionalr6",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Отчет по 6 показателю - "ВСС «Мирный атом — ТРИНИТИ (зимний этап)»"',
                "verbose_name_plural": 'Отчеты по 6 показателю - "ВСС «Мирный атом — ТРИНИТИ (зимний этап)»"',
            },
            bases=("regional_competitions.baseregionalr6",),
        ),
        migrations.CreateModel(
            name="RegionalR6115Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6115",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6115",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Мирный атом — ТРИНИТИ (зимний этап)»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Мирный атом — ТРИНИТИ (зимний этап)»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6114Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6114",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6114",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВСС «Мирный атом (зимний этап)»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВСС «Мирный атом (зимний этап)»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6113Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6113",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6113",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "ВМС «Патриотический центр»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "ВМС «Патриотический центр»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6112Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6112",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6112",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "МССО «Пакш-2»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "МССО «Пакш-2»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6111Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6111",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6111",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "МССО «Тигр»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "МССО «Тигр»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6110Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6110",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6110",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "МССО «Лотос»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "МССО «Лотос»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6109Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6109",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6109",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "МССО «Дюна»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "МССО «Дюна»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6108Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6108",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6108",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "МССО «Босфор»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "МССО «Босфор»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6107Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6107",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6107",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "Петербургский международный газовый форум"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "Петербургский международный газовый форум"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6106Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6106",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6106",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "IV Международный строительный чемпионат"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "IV Международный строительный чемпионат"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6105Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6105",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6105",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "Всероссийская смена студенческих сельскохозяйственных отрядов в рамках Всероссийского форума «Ростов»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "Всероссийская смена студенческих сельскохозяйственных отрядов в рамках Всероссийского форума «Ростов»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6104Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6104",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6104",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "Всероссийский молодёжный форум «Машук», трек «Дружба»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "Всероссийский молодёжный форум «Машук», трек «Дружба»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6103Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6103",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6103",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "Всероссийский молодёжный форум «ОстроVа»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "Всероссийский молодёжный форум «ОстроVа»"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6102Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6102",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6102",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "Праздничное мероприятие, приуроченное к 50-летию начала строительства Байкало-Амурской магистрали"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "Праздничное мероприятие, приуроченное к 50-летию начала строительства Байкало-Амурской магистрали"',
            },
        ),
        migrations.CreateModel(
            name="RegionalR6101Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
                ),
                (
                    "regional_r6101",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="regional_competitions.regionalr6101",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Ссылка по 6 показателю - "Всероссийский образовательный семинар в рамках Молодёжного форума «Алтай: Территория Развития»"',
                "verbose_name_plural": 'Ссылки по 6 показателю - "Всероссийский образовательный семинар в рамках Молодёжного форума «Алтай: Территория Развития»"',
            },
        ),
    ]
