# Generated by Django 4.2.7 on 2024-10-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0028_regionalr6101_regionalr6102_regionalr6103_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dumpstatisticalregionalreport',
            options={'verbose_name': 'Дамп статистического отчета РШ (1 сентября)', 'verbose_name_plural': 'Дампы статистических отчетов РШ (1 сентября)'},
        ),
        migrations.CreateModel(
            name='RegionalR15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveSmallIntegerField(verbose_name='Xп')),
                ('yp', models.PositiveSmallIntegerField(verbose_name='Yп')),
                ('x3', models.PositiveSmallIntegerField(verbose_name='X3')),
                ('y3', models.PositiveSmallIntegerField(verbose_name='Y3')),
                ('p15', models.PositiveSmallIntegerField(verbose_name='P15')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 15 показателю',
                'verbose_name_plural': 'Отчеты по 15 показателю',
            },
        ),
    ]
