# Generated by Django 4.2.7 on 2024-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0029_alter_dumpstatisticalregionalreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr15',
            name='p15',
            field=models.FloatField(verbose_name='P15'),
        ),
    ]
