# Generated by Django 4.2.7 on 2024-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0030_alter_regionalr15_p15'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr2',
            name='full_time_students',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество студентов очной формы обучения'),
        ),
    ]
