# Generated by Django 4.2.7 on 2024-11-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0031_alter_regionalr2_full_time_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='chqrejectinglog',
            name='regional_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_rejecting_reasons', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб'),
        ),
    ]
