# Generated by Django 4.2.7 on 2024-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0032_chqrejectinglog_regional_headquarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='k_place',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Лучшее региональное отделение по комиссарской деятельности'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='overall_place',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Лучшее региональное отделение по итогам года'),
        ),
    ]
