# Generated by Django 4.2.7 on 2024-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regional_competitions", "0033_ranking_k_place_ranking_overall_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="ranking",
            name="r10_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 10 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r11_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 11 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r12_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 12 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r13_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 13 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r14_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 14 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r15_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 15 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r1_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 1 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r2_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 2 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r3_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 3 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r4_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 4 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r5_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 5 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r6_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 6 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r7_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 7 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r8_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 8 показателю"
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="r9_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Очки участника по 9 показателю"
            ),
        ),
    ]
