# Generated by Django 4.2.7 on 2024-11-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0036_regionalheadquarteremail"),
        ("regional_competitions", "0034_ranking_r10_score_ranking_r11_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalR8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Очки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "regional_headquarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.regionalheadquarter",
                        verbose_name="Региональный штаб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 8 показателю",
                "verbose_name_plural": "Отчеты по 8 показателю",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="regionalr8",
            constraint=models.UniqueConstraint(
                fields=("regional_headquarter",), name="unique_regional_headquarter"
            ),
        ),
    ]
