# Generated by Django 4.2.7 on 2024-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0035_regionalr8_regionalr8_unique_regional_headquarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='r16_place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место участника по 16 показателю'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='r16_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Очки участника по 16 показателю'),
        ),
    ]
