# Generated by Django 4.2.7 on 2024-11-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0036_ranking_r16_place_ranking_r16_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='regional_headquarter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regional_competitions_rankings', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб'),
        ),
    ]
