# Generated by Django 4.2.7 on 2024-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0037_alter_ranking_regional_headquarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='sum_k_place',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сумма мест по комиссарской деятельности'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='sum_overall_place',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сумма мест по итогам года'),
        ),
    ]
