# Generated by Django 4.2.7 on 2024-11-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions', '0038_ranking_sum_k_place_ranking_sum_overall_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_place_events', models.PositiveIntegerField(default=0, verbose_name='Кол-во 1-ых мест (мероприятия)')),
                ('second_place_events', models.PositiveIntegerField(default=0, verbose_name='Кол-во 2-ых мест (мероприятия)')),
                ('third_place_events', models.PositiveIntegerField(default=0, verbose_name='Кол-во 3-их мест (мероприятия)')),
                ('first_place_projects', models.PositiveIntegerField(default=0, verbose_name='Кол-во 1-ых мест (трудовые проекты)')),
                ('second_place_projects', models.PositiveIntegerField(default=0, verbose_name='Кол-во 2-ых мест (трудовые проекты)')),
                ('third_place_projects', models.PositiveIntegerField(default=0, verbose_name='Кол-во 3-их мест (трудовые проекты)')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_r7', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Отчет по 7 показателю',
                'verbose_name_plural': 'Отчеты по 7 показателю',
                'ordering': ['regional_headquarter'],
            },
        ),
    ]
