# Generated by Django 4.2.7 on 2024-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0039_regionalr7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr7',
            name='first_place_events',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во 1-ых мест (мероприятия)'),
        ),
        migrations.AlterField(
            model_name='regionalr7',
            name='first_place_projects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во 1-ых мест (трудовые проекты)'),
        ),
        migrations.AlterField(
            model_name='regionalr7',
            name='second_place_events',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во 2-ых мест (мероприятия)'),
        ),
        migrations.AlterField(
            model_name='regionalr7',
            name='second_place_projects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во 2-ых мест (трудовые проекты)'),
        ),
        migrations.AlterField(
            model_name='regionalr7',
            name='third_place_events',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во 3-их мест (мероприятия)'),
        ),
        migrations.AlterField(
            model_name='regionalr7',
            name='third_place_projects',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во 3-их мест (трудовые проекты)'),
        ),
    ]
