# Generated by Django 4.2.7 on 2025-07-31 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regional_competitions',
         '0040_alter_regionalr7_first_place_events_and_more'),
    ]

    operations = [
        # Миграция очищена для предотвращения выполнения в продакшене
        # Изменения будут внесены вручную или через другие миграции
    ]
