# Generated by Django 4.2.7 on 2025-08-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0041_alter_chqrejectinglog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalr61',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский фестиваль студенческой молодежи «Сельскохозяйственный вектор страны»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский фестиваль студенческой молодежи «Сельскохозяйственный вектор страны»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr610',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский слёт студенческих отрядов проводников"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский слёт студенческих отрядов проводников"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6100',
            options={'verbose_name': '6 показатель, отчет РШ - "Митап кураторов трудовых отрядов подростков «Будь в ТОПе!»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Митап кураторов трудовых отрядов подростков «Будь в ТОПе!»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6101',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский образовательный семинар в рамках Молодёжного форума «Алтай: Территория Развития»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский образовательный семинар в рамках Молодёжного форума «Алтай: Территория Развития»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6102',
            options={'verbose_name': '6 показатель, отчет РШ - "Праздничное мероприятие, приуроченное к 50-летию начала строительства Байкало-Амурской магистрали"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Праздничное мероприятие, приуроченное к 50-летию начала строительства Байкало-Амурской магистрали"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6103',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский молодёжный форум «ОстроVа»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский молодёжный форум «ОстроVа»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6104',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский молодёжный форум «Машук», трек «Дружба»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский молодёжный форум «Машук», трек «Дружба»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6105',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская смена студенческих сельскохозяйственных отрядов в рамках Всероссийского форума «Ростов»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская смена студенческих сельскохозяйственных отрядов в рамках Всероссийского форума «Ростов»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6106',
            options={'verbose_name': '6 показатель, отчет РШ - "IV Международный строительный чемпионат"', 'verbose_name_plural': '6 показатель, отчеты РШ - "IV Международный строительный чемпионат"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6107',
            options={'verbose_name': '6 показатель, отчет РШ - "Петербургский международный газовый форум"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Петербургский международный газовый форум"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6108',
            options={'verbose_name': '6 показатель, отчет РШ - "МССО «Босфор»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "МССО «Босфор»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6109',
            options={'verbose_name': '6 показатель, отчет РШ - "МССО «Дюна»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "МССО «Дюна»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr611',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский интенсив сервисного направления"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский интенсив сервисного направления"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6110',
            options={'verbose_name': '6 показатель, отчет РШ - "МССО «Лотос»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "МССО «Лотос»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6111',
            options={'verbose_name': '6 показатель, отчет РШ - "МССО «Тигр»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "МССО «Тигр»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6112',
            options={'verbose_name': '6 показатель, отчет РШ - "МССО «Пакш-2»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "МССО «Пакш-2»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6113',
            options={'verbose_name': '6 показатель, отчет РШ - "ВМС «Патриотический центр»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВМС «Патриотический центр»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6114',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Мирный атом (зимний этап)»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Мирный атом (зимний этап)»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr6115',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Мирный атом — ТРИНИТИ (зимний этап)»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Мирный атом — ТРИНИТИ (зимний этап)»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr612',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский медицинский карьерный форум «Труд крут»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский медицинский карьерный форум «Труд крут»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr613',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская школа высшего командного состава Российских студенческих отрядов для комиссаров региональных отделений»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская школа высшего командного состава Российских студенческих отрядов для комиссаров региональных отделений»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr614',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание руководителей направлений студенческих отрядов проводников"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание руководителей направлений студенческих отрядов проводников"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr615',
            options={'verbose_name': '6 показатель, отчет РШ - "Карьерный форум «Труд крут»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Карьерный форум «Труд крут»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr616',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский форум участников патриотической акции «Снежный десант РСО»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский форум участников патриотической акции «Снежный десант РСО»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr617',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание руководителей направления производственных отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание руководителей направления производственных отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr618',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа инструкторов Всероссийского студенческого отряда проводников"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа инструкторов Всероссийского студенческого отряда проводников"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr619',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа командиров и комиссаров студенческих отрядов железнодорожного транспорта"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа командиров и комиссаров студенческих отрядов железнодорожного транспорта"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr62',
            options={'verbose_name': '6 показатель, отчет РШ - "Образовательный семинар для вожатых студенческих педагогических отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Образовательный семинар для вожатых студенческих педагогических отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr620',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание руководителей региональных штабов МООО «РСО»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание руководителей региональных штабов МООО «РСО»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr621',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа методистов студенческих педагогических отрядов «СПОсобность к действию»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа методистов студенческих педагогических отрядов «СПОсобность к действию»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr622',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание руководителей сервисного направления"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание руководителей сервисного направления"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr623',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский медицинский карьерный форум «Труд крут»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский медицинский карьерный форум «Труд крут»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr624',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание руководителей направлений студенческих педагогических отрядов региональных отделений"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание руководителей направлений студенческих педагогических отрядов региональных отделений"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr625',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский форум студенческих строительных отрядов и Всероссийское совещание руководителей ССО"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский форум студенческих строительных отрядов и Всероссийское совещание руководителей ССО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr626',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа инструкторов Всероссийского студенческого отряда проводников"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа инструкторов Всероссийского студенческого отряда проводников"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr627',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский форум путинных отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский форум путинных отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr628',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание для руководителей сельскохозяйственного направления региональных штабов РСО и руководителей штабов аграрных вузов России"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание для руководителей сельскохозяйственного направления региональных штабов РСО и руководителей штабов аграрных вузов России"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr629',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское совещание-обучение руководителей направления трудовых отрядов подростков"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское совещание-обучение руководителей направления трудовых отрядов подростков"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr63',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский фестиваль студенческих отрядов транспортной отрасли «БАМ – твой второй путь!»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский фестиваль студенческих отрядов транспортной отрасли «БАМ – твой второй путь!»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr630',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский экологический форум студенческих отрядов «ЭкоТОП»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский экологический форум студенческих отрядов «ЭкоТОП»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr631',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская школа подготовки командных составов штабов Всероссийских трудовых проектов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская школа подготовки командных составов штабов Всероссийских трудовых проектов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr632',
            options={'verbose_name': '6 показатель, отчет РШ - "Торжественный этап Всероссийской акции   «Поклонимся великим тем годам» "', 'verbose_name_plural': '6 показатель, отчеты РШ - "Торжественный этап Всероссийской акции   «Поклонимся великим тем годам» "'},
        ),
        migrations.AlterModelOptions(
            name='regionalr633',
            options={'verbose_name': '6 показатель, отчет РШ - "Интенсив Корпоративного университета РСО"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Интенсив Корпоративного университета РСО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr634',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский форум специализированных и производственных отрядов «Работа молодым»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский форум специализированных и производственных отрядов «Работа молодым»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr635',
            options={'verbose_name': '6 показатель, отчет РШ - "Проведение Всероссийского урока труда"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Проведение Всероссийского урока труда"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr636',
            options={'verbose_name': '6 показатель, отчет РШ - "Неделя охраны труда РСО"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Неделя охраны труда РСО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr637',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская школа подготовки руководителей региональных штабов студенческих отрядов – Вышка РСО"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская школа подготовки руководителей региональных штабов студенческих отрядов – Вышка РСО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr638',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская школа по подготовке руководителей сервисных отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская школа по подготовке руководителей сервисных отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr639',
            options={'verbose_name': '6 показатель, отчет РШ - "Тематическое шествие «Май! Труд крут!»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Тематическое шествие «Май! Труд крут!»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr64',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский форум студенческих педагогических отрядов «Вожатская смена: новая высота!»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский форум студенческих педагогических отрядов «Вожатская смена: новая высота!»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr640',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская трудовая акция «Труд крут»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская трудовая акция «Труд крут»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr641',
            options={'verbose_name': '6 показатель, отчет РШ - "Торжественный этап Всероссийской акции  «Поклонимся великим тем годам» »"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Торжественный этап Всероссийской акции  «Поклонимся великим тем годам» »"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr642',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа командиров и комиссаров студенческих строительных отрядов атомной отрасли"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа командиров и комиссаров студенческих строительных отрядов атомной отрасли"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr643',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа командиров и комиссаров студенческих отрядов электросетевого комплекса"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа командиров и комиссаров студенческих отрядов электросетевого комплекса"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr644',
            options={'verbose_name': '6 показатель, отчет РШ - "Школа командиров и комиссаров студенческих отрядов публичного акционерного общества «Газпром»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Школа командиров и комиссаров студенческих отрядов публичного акционерного общества «Газпром»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr645',
            options={'verbose_name': '6 показатель, отчет РШ - "Открытие Всероссийского летнего трудового семестра студенческих отрядов железнодорожного транспорта"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Открытие Всероссийского летнего трудового семестра студенческих отрядов железнодорожного транспорта"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr646',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийское открытие трудового семестра студенческих медицинских отрядов МООО «РСО»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийское открытие трудового семестра студенческих медицинских отрядов МООО «РСО»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr647',
            options={'verbose_name': '6 показатель, отчет РШ - "II Всероссийский слет ветеранов студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "II Всероссийский слет ветеранов студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr648',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский интенсив для руководителей региональных отделений Российских студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский интенсив для руководителей региональных отделений Российских студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr649',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский слет трудовых отрядов подростков"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский слет трудовых отрядов подростков"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr65',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская профориентационная смена «Труд крут»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская профориентационная смена «Труд крут»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr650',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская медиашкола Российских студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская медиашкола Российских студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr651',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская медиашкола Российских студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская медиашкола Российских студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr652',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский слет студенческих отрядов нефтедобывающей отрасли"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский слет студенческих отрядов нефтедобывающей отрасли"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr653',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский слет студенческих медицинских отрядов «Всегда 20»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский слет студенческих медицинских отрядов «Всегда 20»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr654',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский конкурс профессионального мастерства «Труд крут» в направлении СПрО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr655',
            options={'verbose_name': '6 показатель, отчет РШ - "Слёт студенческих отрядов ПАО «Газпром»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Слёт студенческих отрядов ПАО «Газпром»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr656',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский форум студенческих педагогических отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский форум студенческих педагогических отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr657',
            options={'verbose_name': '6 показатель, отчет РШ - "Торжественный этап Всероссийской акции  «Поклонимся великим тем годам» »"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Торжественный этап Всероссийской акции  «Поклонимся великим тем годам» »"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr658',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская научная конференция студенческих отрядов, посвященная 65-летию движения студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская научная конференция студенческих отрядов, посвященная 65-летию движения студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr659',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПрО «Арктика»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПрО «Арктика»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr66',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский Слет студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский Слет студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr660',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПрО «КАМАЗ»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПрО «КАМАЗ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr661',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПрО «Алабуга – Композит»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПрО «Алабуга – Композит»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr662',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Мирный атом»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Мирный атом»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr663',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Мирный атом – ПРОРЫВ»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Мирный атом – ПРОРЫВ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr664',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Мирный атом – ЛАЭС»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Мирный атом – ЛАЭС»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr665',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «СКИФ»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «СКИФ»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr666',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Север»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Север»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr667',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «Сибирь»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «Сибирь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr668',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСС «БАМ 2.0»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСС «БАМ 2.0»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr669',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПО «Артек»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПО «Артек»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr67',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский конкурс профессионального мастерства «Труд крут» по девяти направлениям деятельности"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский конкурс профессионального мастерства «Труд крут» по девяти направлениям деятельности"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr670',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПО «Дельфин.ru»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПО «Дельфин.ru»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr671',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПО «Гагарин»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПО «Гагарин»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr672',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПО «Океан»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПО «Океан»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr673',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПО «Орлёнок»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПО «Орлёнок»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr674',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСПО «Сириус»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСПО «Сириус»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr675',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСССхО «Агроном-сад»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСССхО «Агроном-сад»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr676',
            options={'verbose_name': '6 показатель, отчет РШ - "ВССхО «МоСт» (Молочный стандарт)"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВССхО «МоСт» (Молочный стандарт)"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr677',
            options={'verbose_name': '6 показатель, отчет РШ - "ВССПуО «Край Света»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВССПуО «Край Света»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr678',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСССервО «Мрия»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСССервО «Мрия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr679',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСССервО «Метрополь»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСССервО «Метрополь»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr68',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская спартакиада студенческих отрядов"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская спартакиада студенческих отрядов"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr680',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСССервО «Сочи Парк Отель»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСССервО «Сочи Парк Отель»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr681',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСССервО «Взлетная полоса»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСССервО «Взлетная полоса»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr682',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСССервО «Первый рассвет»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСССервО «Первый рассвет»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr683',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Атлант»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Атлант»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr684',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Академия»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Академия»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr685',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Аметист»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Аметист»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr686',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Сердце Пармы»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Сердце Пармы»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr687',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Белогорье»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Белогорье»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr688',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Коллеги»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Коллеги»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr689',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Призвание»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Призвание»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr69',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийский слет студенческих отрядов образовательных организаций аграрного профиля Российской Федерации «Студагро»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийский слет студенческих отрядов образовательных организаций аграрного профиля Российской Федерации «Студагро»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr690',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Клиника»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Клиника»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr691',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСФО «36,6»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСФО «36,6»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr692',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСМО «Галиотис»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСМО «Галиотис»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr693',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСОП Екатеринбург"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСОП Екатеринбург"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr694',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСОП Нижний Новгород"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСОП Нижний Новгород"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr695',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСОП Москва"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСОП Москва"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr696',
            options={'verbose_name': '6 показатель, отчет РШ - "ВСОП Санкт-Петербург"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВСОП Санкт-Петербург"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr697',
            options={'verbose_name': '6 показатель, отчет РШ - "ВПТОП «АлабугаТОП»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "ВПТОП «АлабугаТОП»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr698',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская патриотическая акция «Снежный десант РСО»"', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская патриотическая акция «Снежный десант РСО»"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr699',
            options={'verbose_name': '6 показатель, отчет РШ - "Всероссийская патриотическая акция «Поклонимся великим тем годам» "', 'verbose_name_plural': '6 показатель, отчеты РШ - "Всероссийская патриотическая акция «Поклонимся великим тем годам» "'},
        ),
        migrations.AlterModelOptions(
            name='regionalr91',
            options={'verbose_name': '9 показатель, отчет РШ - "Снежный десант РСО"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Снежный десант РСО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr911',
            options={'verbose_name': '9 показатель, отчет РШ - "Мероприятие по развитию направления ТОП в субъекте Российской Федерации"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Мероприятие по развитию направления ТОП в субъекте Российской Федерации"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr92',
            options={'verbose_name': '9 показатель, отчет РШ - "Творческий фестиваль"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Творческий фестиваль"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr93',
            options={'verbose_name': '9 показатель, отчет РШ - "Спартакиада студенческих отрядов и комплекс мероприятий РСО-спорт"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Спартакиада студенческих отрядов и комплекс мероприятий РСО-спорт"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr94',
            options={'verbose_name': '9 показатель, отчет РШ - "Конкурс профессионального мастерства"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Конкурс профессионального мастерства"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr95',
            options={'verbose_name': '9 показатель, отчет РШ - "День РСО"', 'verbose_name_plural': '9 показатель, отчеты РШ - "День РСО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr96',
            options={'verbose_name': '9 показатель, отчет РШ - "Региональная школа подготовки командиров и комиссаров РСО"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Региональная школа подготовки командиров и комиссаров РСО"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr97',
            options={'verbose_name': '9 показатель, отчет РШ - "Открытие трудового семестра"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Открытие трудового семестра"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr98',
            options={'verbose_name': '9 показатель, отчет РШ - "Закрытие трудового семестра"', 'verbose_name_plural': '9 показатель, отчеты РШ - "Закрытие трудового семестра"'},
        ),
    ]
