# Generated by Django 4.2.7 on 2025-08-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions', '0041_alter_chqrejectinglog_user'),
    ]

    operations = [
        # Миграция очищена для предотвращения выполнения в продакшене
        # Изменения verbose_name будут внесены вручную или через другие миграции
    ]
