# Generated by Django 4.2.7 on 2025-08-05 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions_2025', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '17 показатель, отчет РШ',
                'verbose_name_plural': '17 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR91',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Творческий фестиваль (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Творческий фестиваль (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR910',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Всероссийская трудовая акция «ТрудКрут» или организация шествия 1 Мая в субъекте РФ (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Всероссийская трудовая акция «ТрудКрут» или организация шествия 1 Мая в субъекте РФ (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR92',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Спартакиада студенческих отрядов и участие в комплексе мероприятий РСО-спорт (организация мероприятия, в случае проведения)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Спартакиада студенческих отрядов и участие в комплексе мероприятий РСО-спорт (организация мероприятия, в случае проведения)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR93',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Конкурс профессионального мастерства (по любому из направлений деятельности РСО)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Конкурс профессионального мастерства (по любому из направлений деятельности РСО)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR94',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "День РСО / Карьерный форум (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "День РСО / Карьерный форум (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR95',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Региональная школа подготовки командиров и комиссаров РСО (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Региональная школа подготовки командиров и комиссаров РСО (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR96',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Открытие трудового семестра (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Открытие трудового семестра (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR97',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Закрытие трудового семестра (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Закрытие трудового семестра (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR98',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Всероссийская неделя охраны труда РСО (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Всероссийская неделя охраны труда РСО (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR99',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('event_happened', models.BooleanField(default=False, verbose_name='Проведение акции')),
                ('document', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан документа, подтверждающего проведение мероприятия')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '9 показатель, отчет РШ - "Всероссийский урок труда (организация мероприятия)"',
                'verbose_name_plural': '9 показатель, отчеты РШ - "Всероссийский урок труда (организация мероприятия)"',
            },
        ),
        migrations.AlterModelOptions(
            name='regionalr101',
            options={'verbose_name': '10 показатель, отчет РШ - "Снежный Десант"', 'verbose_name_plural': '10 показатель, отчеты РШ - "Снежный Десант"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr102',
            options={'verbose_name': '10 показатель, отчет РШ - "Поклонимся великим тем годам"', 'verbose_name_plural': '10 показатель, отчеты РШ - "Поклонимся великим тем годам"'},
        ),
        migrations.AlterModelOptions(
            name='regionalr11',
            options={'verbose_name': '11 показатель, отчет РШ', 'verbose_name_plural': '11 показатель, отчеты РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr2',
            options={'verbose_name': '2 показатель, отчет РШ', 'verbose_name_plural': '2 показатель, отчеты РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr4',
            options={'verbose_name': '4 показатель, отчет РШ', 'verbose_name_plural': '4 показатель, отчеты РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr4event',
            options={'verbose_name': '4 показатель, мероприятие РШ', 'verbose_name_plural': '4 показатель, мероприятия РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr5',
            options={'verbose_name': '5 показатель, отчет РШ', 'verbose_name_plural': '5 показатель, отчеты РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr5event',
            options={'verbose_name': '5 показатель, проект РШ', 'verbose_name_plural': '5 показатель, проекты РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr7',
            options={'ordering': ['regional_headquarter'], 'verbose_name': '7 показатель, отчет РШ', 'verbose_name_plural': '7 показатель, отчеты РШ'},
        ),
        migrations.AlterModelOptions(
            name='regionalr8',
            options={'ordering': ['-created_at'], 'verbose_name': '8 показатель, отчет РШ', 'verbose_name_plural': '8 показатель, отчеты РШ'},
        ),
        migrations.CreateModel(
            name='RegionalR99Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r99', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr99', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Всероссийский урок труда (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Всероссийский урок труда (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR98Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r98', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr98', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Всероссийская неделя охраны труда РСО (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Всероссийская неделя охраны труда РСО (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR97Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r97', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr97', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Закрытие трудового семестра (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Закрытие трудового семестра (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR96Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r96', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr96', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Открытие трудового семестра (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Открытие трудового семестра (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR95Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r95', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr95', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Региональная школа подготовки командиров и комиссаров РСО (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Региональная школа подготовки командиров и комиссаров РСО (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR94Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r94', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr94', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "День РСО / Карьерный форум (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "День РСО / Карьерный форум (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR93Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r93', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr93', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Конкурс профессионального мастерства (по любому из направлений деятельности РСО)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Конкурс профессионального мастерства (по любому из направлений деятельности РСО)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR92Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r92', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr92', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Спартакиада студенческих отрядов и участие в комплексе мероприятий РСО-спорт (организация мероприятия, в случае проведения)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Спартакиада студенческих отрядов и участие в комплексе мероприятий РСО-спорт (организация мероприятия, в случае проведения)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR91Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r91', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr91', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Творческий фестиваль (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Творческий фестиваль (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR910Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='URL-адрес')),
                ('regional_r910', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr910', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Ссылка по 9 показателю - "Всероссийская трудовая акция «ТрудКрут» или организация шествия 1 Мая в субъекте РФ (организация мероприятия)"',
                'verbose_name_plural': 'Ссылки по 9 показателю - "Всероссийская трудовая акция «ТрудКрут» или организация шествия 1 Мая в субъекте РФ (организация мероприятия)"',
            },
        ),
        migrations.CreateModel(
            name='RegionalR20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('premises_available', models.BooleanField(default=False, help_text='Выбрано - есть, пусто - нет', verbose_name='Наличие помещения')),
                ('equipped_workplaces', models.BooleanField(default=False, help_text='Выбрано - есть, пусто - нет', verbose_name='Наличие оборудованных рабочих мест')),
                ('event_spaces', models.BooleanField(default=False, help_text='Выбрано - есть, пусто - нет', verbose_name='Наличие доступа к помещениям для совместной работы и проведения мероприятий различного уровня')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '20 показатель, отчет РШ',
                'verbose_name_plural': '20 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('employees_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Фактическое количество сотрудников РО РСО')),
                ('officially_employed', models.BooleanField(default=False, help_text='Выбрано - трудоустроены официально, пусто - неофициально', verbose_name='Официальное трудоустройство сотрудников в РО РСО')),
                ('average_salary', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Средняя заработная плата сотрудников РО РСО, руб.')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '19 показатель, отчет РШ',
                'verbose_name_plural': '19 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('employed_student_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество трудоустроенных студентов в третий трудовой семестр')),
                ('employed_student_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество трудоустроенных в штат принимающей организации по итогам третьего трудового семестра')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '18 показатель, отчет РШ',
                'verbose_name_plural': '18 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR17Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Файл')),
                ('regional_r17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='regional_competitions_2025.regionalr17', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Проект по 17 показателю',
                'verbose_name_plural': 'Проекты по 17 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR17Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на публикацию')),
                ('regional_r17_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr17project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ссылка по 17 показателю',
                'verbose_name_plural': 'Ссылки по 17 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveSmallIntegerField(verbose_name='Xп')),
                ('yp', models.PositiveSmallIntegerField(verbose_name='Yп')),
                ('x3', models.PositiveSmallIntegerField(verbose_name='X3')),
                ('y3', models.PositiveSmallIntegerField(verbose_name='Y3')),
                ('p15', models.FloatField(verbose_name='P15')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '13 показатель, отчет РШ',
                'verbose_name_plural': '13 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount_of_money', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем средств собранных бойцами РО РСО')),
                ('number_of_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество членов РО РСО, принявших участие')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан подтверждающего документа')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '12 показатель, отчет РШ',
                'verbose_name_plural': '12 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount_of_money', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма уплаченных членских взносов')),
                ('participants_with_payment', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество членов РО РСО с уплаченными членскими взносами')),
                ('foreign_participants', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Численность иностранных граждан')),
                ('top_participants', models.PositiveSmallIntegerField(blank=True, help_text='Участники из ТОП - это участники из Трудовых Отрядов Подростков', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Численность участников из ТОП')),
                ('top_must_pay', models.BooleanField(default=False, help_text='Если выбрано, то участники из ТОП не будут учитываться при расчете количества участников с уплаченными членскими взносами', verbose_name='ТОП освобождены от оплаты членских взносов в данном РО')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Скан подтверждающего документа')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '1 показатель, отчет РШ',
                'verbose_name_plural': '1 показатель, отчеты РШ',
            },
        ),
    ]
