# Generated by Django 4.2.7 on 2025-08-05 16:30

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions_2025', '0002_regionalr17_regionalr91_regionalr910_regionalr92_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Документ')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '16 показатель, отчет РШ',
                'verbose_name_plural': '16 показатель, отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='RegionalR14Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Наименование проекта, в котором ЛСО РО одержал победу')),
                ('project_scale', models.CharField(blank=True, choices=[('Всероссийский', 'Всероссийский'), ('Окружной', 'Окружной'), ('Межрегиональный', 'Межрегиональный')], max_length=30, null=True, verbose_name='Масштаб проекта')),
                ('regulations', models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_comp_regulations_files_path, verbose_name='Положение о проекте')),
                ('regional_r14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='regional_competitions_2025.regionalr16', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Проект по 14 показателю',
                'verbose_name_plural': 'Проекты по 14 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR14Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на группу проекта в социальных сетях')),
                ('regional_r14_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regional_competitions_2025.regionalr14project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Ссылка по 14 показателю',
                'verbose_name_plural': 'Ссылки по 14 показателю',
            },
        ),
        migrations.CreateModel(
            name='RegionalR14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен на верификацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('verified_by_chq', models.BooleanField(null=True, verbose_name='Верифицирован ЦШ')),
                ('verified_by_dhq', models.BooleanField(default=False, verbose_name='Верифицирован ОШ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_project', models.BooleanField(default=False, verbose_name='Наличие трудового проекта, в котором ЛО РСО одержал победу')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '14 показатель, отчет РШ',
                'verbose_name_plural': '14 показатель, отчеты РШ',
            },
        ),
    ]
