# Generated by Django 4.2.7 on 2025-08-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0003_regionalr16_regionalr14project_regionalr14link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr14project',
            name='regional_r14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='regional_competitions_2025.regionalr14', verbose_name='Отчет'),
        ),
    ]
