# Generated by Django 4.2.7 on 2025-08-07 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions_2025', '0004_alter_regionalr14project_regional_r14'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr12',
            name='amount_of_money',
            field=models.FloatField(blank=True, help_text='Очки в данном показателе это занятое место', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем средств собранных бойцами РО РСО'),
        ),
        migrations.CreateModel(
            name='RegionalR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('employed_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество трудоустроенных членов РО РСО')),
                ('r3_place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в рейтинге P3')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
                ('regional_r1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regional_competitions_2025.regionalr1', verbose_name='Региональный отчет №1')),
            ],
            options={
                'verbose_name': '3 показатель, отчет РШ',
                'verbose_name_plural': '3 показатель, отчеты РШ',
            },
        ),
    ]
