# Generated by Django 4.2.7 on 2025-08-12 15:15

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions_2025', '0005_alter_regionalr12_amount_of_money_regionalr3'),
    ]

    operations = [
        # Миграция помечена как примененная с помощью --fake
        # Содержимое очищено для предотвращения выполнения в продакшене
    ]
