# Generated by Django 4.2.7 on 2025-08-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0006_regionalr911_regionalr912_regionalr913_regionalr914_and_more'),
    ]

    operations = [
        # Миграция помечена как примененная с помощью --fake
        # Содержимое очищено для предотвращения выполнения в продакшене
    ]
