# Generated by Django 4.2.7 on 2025-08-13 12:11

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions_2025', '0008_baseregionalr6_regionalr61_regionalr610_regionalr611_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalR15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество трудоустроенных и прошедших профобучение членов РО')),
                ('training_quota', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая квота профобучения на 1 сентября 2025')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='P15')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': '15 показатель, отчет РШ',
                'verbose_name_plural': '15 показатель, отчеты РШ',
            },
        ),
    ]
