# Generated by Django 4.2.7 on 2025-08-16 11:08

from django.db import migrations, models
import django.db.models.deletion
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('regional_competitions_2025', '0009_regionalr15'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr19',
            name='officially_employed',
            field=models.BooleanField(blank=True, default=False, help_text='Выбрано - трудоустроены официально, пусто - неофициально', null=True, verbose_name='Официальное трудоустройство сотрудников в РО РСО'),
        ),
        migrations.AlterField(
            model_name='regionalr20',
            name='equipped_workplaces',
            field=models.BooleanField(blank=True, default=False, help_text='Выбрано - есть, пусто - нет', null=True, verbose_name='Наличие оборудованных рабочих мест'),
        ),
        migrations.AlterField(
            model_name='regionalr20',
            name='event_spaces',
            field=models.BooleanField(blank=True, default=False, help_text='Выбрано - есть, пусто - нет', null=True, verbose_name='Наличие доступа к помещениям для совместной работы и проведения мероприятий различного уровня'),
        ),
        migrations.CreateModel(
            name='StatisticalRegionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField(verbose_name='Количество членов регионального отделения')),
                ('employed_sso', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССО')),
                ('employed_spo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СПО')),
                ('employed_sop', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СОП')),
                ('employed_smo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СМО')),
                ('employed_sservo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССервО')),
                ('employed_ssho', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССхО')),
                ('employed_specialized_detachments', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, профильные отряды')),
                ('employed_production_detachments', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, производственные отряды')),
                ('employed_top', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, ТОП')),
                ('employed_so_poo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов СО ПОО')),
                ('employed_so_oovo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов СО ООВО')),
                ('employed_ro_rso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов РО РСО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Статистический отчет РШ',
                'verbose_name_plural': 'Статистические отчеты РШ',
            },
        ),
        migrations.CreateModel(
            name='DumpStatisticalRegionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField(verbose_name='Количество членов регионального отделения')),
                ('employed_sso', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССО')),
                ('employed_spo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СПО')),
                ('employed_sop', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СОП')),
                ('employed_smo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных СМО')),
                ('employed_sservo', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССервО')),
                ('employed_ssho', models.PositiveIntegerField(verbose_name='Количество трудоустроенных ССхО')),
                ('employed_specialized_detachments', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, профильные отряды')),
                ('employed_production_detachments', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, производственные отряды')),
                ('employed_top', models.PositiveIntegerField(verbose_name='Количество трудоустроенных, ТОП')),
                ('employed_so_poo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов СО ПОО')),
                ('employed_so_oovo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов СО ООВО')),
                ('employed_ro_rso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество работников штабов РО РСО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('r_competition', models.ForeignKey(default=regional_competitions_2025.utils.get_last_rcompetition_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='regional_competitions_2025.rcompetition', verbose_name='Рейтинг РО')),
                ('regional_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб')),
            ],
            options={
                'verbose_name': 'Дамп статистического отчета РШ (1 сентября)',
                'verbose_name_plural': 'Дампы статистических отчетов РШ (1 сентября)',
            },
        ),
        migrations.CreateModel(
            name='AdditionalStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.PositiveIntegerField(verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('statistical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_statistics', to='regional_competitions_2025.statisticalregionalreport', verbose_name='Статистический отчет')),
            ],
            options={
                'verbose_name': 'Свои варианты - статистический отчет',
                'verbose_name_plural': 'Свои варианты - статистические отчеты',
            },
        ),
        migrations.AddConstraint(
            model_name='statisticalregionalreport',
            constraint=models.UniqueConstraint(fields=('r_competition', 'regional_headquarter'), name='unique_rcompetition_rhq'),
        ),
        migrations.AddConstraint(
            model_name='dumpstatisticalregionalreport',
            constraint=models.UniqueConstraint(fields=('r_competition', 'regional_headquarter'), name='unique_rcompetition_rhq_dump'),
        ),
    ]
