# Generated by Django 4.2.7 on 2025-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0010_alter_regionalr19_officially_employed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalr3',
            name='regional_r1',
        ),
        migrations.AlterField(
            model_name='regionalr19',
            name='average_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Средняя заработная плата сотрудников РО РСО, руб.'),
        ),
        migrations.AlterField(
            model_name='regionalr20',
            name='premises_available',
            field=models.BooleanField(blank=True, default=False, help_text='Выбрано - есть, пусто - нет', null=True, verbose_name='Наличие помещения'),
        ),
    ]
