# Generated by Django 4.2.7 on 2025-08-20 17:59

from django.db import migrations, models
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0011_remove_regionalr3_regional_r1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_production_detachments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные, производственные отряды'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_smo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные СМО'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_sop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные СОП'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_specialized_detachments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные, профильные отряды'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_spo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные СПО'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_sservo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные ССервО'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_ssho',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные ССхО'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_sso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные ССО'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='learned_top',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные, ТОП'),
        ),
        migrations.AddField(
            model_name='dumpstatisticalregionalreport',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_supporting_docs_files_path, verbose_name='Документы, подтверждающие факт трудоустройства, по каждому направлению'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_production_detachments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные, производственные отряды'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_smo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные СМО'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_sop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные СОП'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_specialized_detachments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные, профильные отряды'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_spo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные СПО'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_sservo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные ССервО'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_ssho',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные ССхО'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_sso',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные ССО'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='learned_top',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошедшие обучение ЦШ и трудоустроенные, ТОП'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to=regional_competitions_2025.utils.regional_supporting_docs_files_path, verbose_name='Документы, подтверждающие факт трудоустройства, по каждому направлению'),
        ),
    ]
