# Generated by Django 4.2.7 on 2025-08-24 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0012_dumpstatisticalregionalreport_learned_production_detachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalr1',
            name='detachment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='employed_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество трудоустроенных членов РО РСО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='foreign_must_pay',
            field=models.BooleanField(default=False, help_text='Если выбрано, то иностранные граждане не будут учитываться при расчете количества участников с уплаченными членскими взносами', verbose_name='Иностранные граждане освобождены от оплаты членских взносов в данном РО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='production_detachment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество производственных отрядов'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='production_detachment_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников производственных отрядов'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='smo_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов СМО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='smo_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников СМО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='sop_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов СОП'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='sop_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников СОП'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='specialized_detachment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество профильных отрядов'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='specialized_detachment_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников профильных отрядов'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='spo_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов СПО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='spo_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников СПО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='sservo_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов ССервО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='sservo_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников ССервО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='ssho_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов ССхО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='ssho_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников ССхО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='sso_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов ССО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='sso_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников ССО'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='top_detachment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отрядов ТОП'),
        ),
        migrations.AddField(
            model_name='regionalr1',
            name='top_detachment_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество участников ТОП'),
        ),
        migrations.AddField(
            model_name='regionalr19',
            name='officially_employed_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество сотрудников, официально трудоустроенных в РО РСО'),
        ),
        migrations.AlterField(
            model_name='regionalr19',
            name='officially_employed',
            field=models.BooleanField(blank=True, default=False, help_text='Селект больше не используется.', null=True, verbose_name='Официальное трудоустройство сотрудников в РО РСО'),
        ),
    ]
