# Generated by Django 4.2.7 on 2025-08-24 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0013_regionalr1_detachment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr1',
            name='participants_with_payment',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Считается автоматически, если заполнено поле "Сумма уплаченных членских взносов"', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество членов РО РСО с уплаченными членскими взносами'),
        ),
        migrations.CreateModel(
            name='RegionalR19Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('salary', models.PositiveIntegerField(verbose_name='Заработная плата')),
                ('regional_r19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='regional_competitions_2025.regionalr19', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Зарплата сотрудника РО РСО',
                'verbose_name_plural': 'Зарплаты сотрудников РО РСО',
            },
        ),
    ]
