# Generated by Django 4.2.7 on 2025-08-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0014_alter_regionalr1_participants_with_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлен на верификацию'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='score',
            field=models.FloatField(default=0, verbose_name='Очки'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='verified_by_chq',
            field=models.BooleanField(null=True, verbose_name='Верифицирован ЦШ'),
        ),
        migrations.AddField(
            model_name='statisticalregionalreport',
            name='verified_by_dhq',
            field=models.BooleanField(default=False, verbose_name='Верифицирован ОШ'),
        ),
    ]
