# Generated by Django 4.2.7 on 2025-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0015_statisticalregionalreport_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalr19employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='regionalr19employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Заработная плата'),
        ),
    ]
