# Generated by Django 4.2.7 on 2025-08-29 10:11

from django.db import migrations, models
import regional_competitions_2025.utils


class Migration(migrations.Migration):

    dependencies = [
        ('regional_competitions_2025', '0016_alter_regionalr19employee_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpstatisticalregionalreport',
            name='supporting_documents',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=regional_competitions_2025.utils.regional_supporting_docs_files_path, verbose_name='Документы, подтверждающие факт трудоустройства, по каждому направлению'),
        ),
        migrations.AlterField(
            model_name='statisticalregionalreport',
            name='supporting_documents',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=regional_competitions_2025.utils.regional_supporting_docs_files_path, verbose_name='Документы, подтверждающие факт трудоустройства, по каждому направлению'),
        ),
    ]
