# Generated by Django 4.2.7 on 2024-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_address_alter_event_format'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventorganizationdata',
            constraint=models.UniqueConstraint(fields=('event', 'organizer'), name='unique_event_organizer'),
        ),
    ]
