# Generated by Django 4.2.7 on 2024-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventorganizationdata_unique_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='conference_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на конференцию'),
        ),
    ]
