# Generated by Django 4.2.7 on 2024-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_available_structural_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_structural_units',
            field=models.CharField(blank=True, choices=[('Отряды', 'Отряды'), ('Образовательные штабы', 'Образовательные штабы'), ('Местные штабы', 'Местные штабы'), ('Региональные штабы', 'Региональные штабы'), ('Окружные штабы', 'Окружные штабы'), ('Центральные штабы', 'Центральные штабы')], default='Отряды', max_length=30, null=True, verbose_name='Объекты, имеющие возможность формировать групповые заявки'),
        ),
    ]
