# Generated by Django 4.2.7 on 2024-06-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
