# Generated by Django 4.2.7 on 2024-04-06 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_usereducation_study_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForeignParentDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Документ, удостоверяющий личность')),
                ('snils', models.CharField(blank=True, max_length=30, null=True, verbose_name='СНИЛС')),
                ('inn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ИНН')),
                ('foreign_pass_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия и номер')),
                ('foreign_pass_whom', models.CharField(blank=True, max_length=230, null=True, verbose_name='Кем выдан')),
                ('foreign_pass_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('work_book_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Трудовая книжка: серия, номер')),
                ('child_docs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_child_docs', to='users.userforeigndocuments', verbose_name='Документы несоверешеннолетнего иностранного пользователя')),
                ('child_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_parent_documents', to=settings.AUTH_USER_MODEL, verbose_name='Несоверешнный пользователь')),
            ],
            options={
                'verbose_name': 'Документ законного представителя иностранного пользователя',
                'verbose_name_plural': 'Документы законного представителя иностранного пользователя',
            },
        ),
        migrations.CreateModel(
            name='AdditionalForeignDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_doc_name', models.CharField(max_length=500, verbose_name='Название документа')),
                ('foreign_doc_num', models.CharField(max_length=500, verbose_name='Номер, дата и тд.')),
                ('foreign_docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_foreign_docs', to='users.userforeignparentdocs', verbose_name='Документы представителя несовершеннолетнего иностранного пользователя')),
            ],
            options={
                'verbose_name': 'Дополнительный документ иностранного пользователя',
                'verbose_name_plural': 'Дополнительные документы иностранного пользователя',
            },
        ),
    ]
