# Generated by Django 4.2.7 on 2024-04-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userforeignparentdocs_additionalforeigndocs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userforeignparentdocs',
            name='child_docs',
        ),
    ]
