# Generated by Django 4.2.7 on 2024-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_userforeigndocuments_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsouser',
            name='reports_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к странице с отчетами'),
        ),
    ]
