# Generated by Django 4.2.7 on 2024-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_userforeignparentdocs_child_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userforeignparentdocs',
            old_name='child_user',
            new_name='user',
        ),
    ]
