# Generated by Django 4.2.7 on 2024-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_rename_child_user_userforeignparentdocs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforeignparentdocs',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Документ, удостоверяющий личность'),
        ),
    ]
