from django.urls import path

from reports.views import (AttributesOfUniformDataView, CommanderSchoolView,
                           DetachmentQResultsView,
                           ExportCommanderSchoolDataView,
                           ExportCompetitionParticipantsContactData,
                           ExportCompetitionParticipantsDataView,
                           ExportDetachmentQResultsView,
                           ExportMembershipFeeDataView,
                           ExportSafetyTestResultsView,
                           ReportView, MembershipFeeDataView,
                           SafetyTestResultsView, TaskStatusView,
                           ExportQ5DataView, ExportQ6DataView, ExportQ7DataView, ExportQ8DataView, ExportQ9DataView, ExportQ10DataView, ExportQ11DataView, ExportQ12DataView, ExportQ15DataView,
                           ExportQ16DataView, ExportQ17DataView,
                           ExportQ18DataView,
                           CompetitionParticipantView,
                           ExportAttributesOfUniformView,
                           ExportQ13DataView, ExportQ14DataView,
                           ExportQ19DataView, ExportCentralHqDataView, ExportDistrictHqDataView,
                           ExportRegionalHqDataView, ExportLocalHqDataView, ExportEducationHqDataView,
                           ExportDetachmentDataView)


urlpatterns = [
    path('', ReportView.as_view(), name='reports'),
    path(
        'task-status/<str:task_id>/',
        TaskStatusView.as_view(),
        name='task_status'
    ),
    path(
        'safety_test_results/',
        SafetyTestResultsView.as_view(),
        name='safety_test_results'
    ),
    path(
        'safety_test_results/export/',
        ExportSafetyTestResultsView.as_view(),
        name='export_safety_test_results'
    ),
    path(
        'competition_participants/',
        CompetitionParticipantView.as_view(),
        name='competition_participants'
    ),
    path(
        'competition_participants/export/',
        ExportCompetitionParticipantsDataView.as_view(),
        name='export_competition_participants_results'
    ),
    path(
        'detachment_q_results/',
        DetachmentQResultsView.as_view(),
        name='detachment_q_results'
    ),
    path(
        'detachment_q_results/export/',
        ExportDetachmentQResultsView.as_view(),
        name='export_detachment_q_results'
    ),
    path(
        'competition_participants/contact_data/export/',
        ExportCompetitionParticipantsContactData.as_view(),
        name='competition_participants_contact_data'
    ),
    path(
        'commander_shool/export/',
        ExportCommanderSchoolDataView.as_view(),
        name='export_commander_school_results'
    ),
    path(
        'commander_shool/',
        CommanderSchoolView.as_view(),
        name='commander_school'
    ),
    path(
        'get_q5_data/export/',
        ExportQ5DataView.as_view(),
        name='export_q5_data'
    ),
    path(
        'get_q6_data/export/',
        ExportQ6DataView.as_view(),
        name='export_q6_data'
    ),
     path(
        'get_q7_data/export/',
        ExportQ7DataView.as_view(),
        name='export_q7_data'
    ),
    path(
        'get_q8_data/export/',
        ExportQ8DataView.as_view(),
        name='export_q8_data'
    ),
    path(
        'get_q9_data/export/',
        ExportQ9DataView.as_view(),
        name='export_q9_data'
    ),
    path(
        'get_q10_data/export/',
        ExportQ10DataView.as_view(),
        name='export_q10_data'
    ),
    path(
        'get_q11_data/export/',
        ExportQ11DataView.as_view(),
        name='export_q11_data'
    ),
    path(
        'get_q12_data/export/',
        ExportQ12DataView.as_view(),
        name='export_q12_data'
    ),
    path(
        'get_q13_data/export/',
        ExportQ13DataView.as_view(),
        name='export_q13_data'
    ),
    path(
        'get_q14_data/export/',
        ExportQ14DataView.as_view(),
        name='export_q14_data'
    ),
    path(
        'get_q15_data/export/',
        ExportQ15DataView.as_view(),
        name='export_q15_data'
    ),
    path(
        'get_q16_data/export/',
        ExportQ16DataView.as_view(),
        name='export_q16_data'
    ),
    path(
        'get_q17_data/export/',
        ExportQ17DataView.as_view(),
        name='export_q17_data'
    ),
    path(
        'get_q18_data/export/',
        ExportQ18DataView.as_view(),
        name='export_q18_data'
    ),
    path(
        'get_q19_data/export/',
        ExportQ19DataView.as_view(),
        name='export_q19_data'
    ),
    path(
        'membership_fee/export/',
        ExportMembershipFeeDataView.as_view(),
        name='membership_fee_export'
    ),
    path(
        'membership_fee/',
        MembershipFeeDataView.as_view(),
        name='membership_fee'
    ),
    path('attributes_of_uniform/export/',
         ExportAttributesOfUniformView.as_view(),
         name='attributes_of_uniform_export'),
    path(
        'attributes_of_uniform/',
        AttributesOfUniformDataView.as_view(),
        name='attributes_of_uniform'
    ),
     path('central_headquarters/export/',
         ExportCentralHqDataView.as_view(),
         name='central_hq_export'),
    path('district_headquarters/export/',
         ExportDistrictHqDataView.as_view(), 
         name='district_hq_export'),
    path('regional_headquarters/export/',
         ExportRegionalHqDataView.as_view(),
         name='regional_hq_export'),
    path('local_headquarters/export/',
         ExportLocalHqDataView.as_view(),
         name='local_hq_export'),
    path('education_headquarters/export/',
         ExportEducationHqDataView.as_view(),
         name='education_hq_export'),
    path('detachment/export/',
         ExportDetachmentDataView.as_view(),
         name='detachment_export'),
]
