# Generated by Django 4.2.7 on 2024-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answeroption_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Получены ответы по попытке'),
        ),
    ]
