name: dev RSO backend CD
on:
  push:
    branches:
      - dev
jobs:
  build_backend_and_push_to_docker_hub:
    name: Push backend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./rso_backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rso_backend:dev
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - build_backend_and_push_to_docker_hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dev_infra/docker-compose.yml"
          target: /root/rso_dev
      - name: Copy nginx.conf
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dev_infra/nginx.conf"
          target: /root/rso_dev
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd rso_dev
            sudo docker compose down
            sudo docker system prune -f
            sudo docker image prune -f
            sudo docker compose pull
            sudo docker compose up -d
            sudo docker compose exec backend python manage.py migrate
            sudo docker compose exec backend python manage.py collectstatic
            sudo docker compose exec backend cp -r /app/collected_static/. /backend_static/static/
  post_deploy_tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make regions get request
        id: regions_request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://213.139.208.147:30000/api/v1/regions/'
          method: 'GET'

      - name: Get commit author name
        id: get_author
        run: |
          author_name=$(git log -1 --pretty=format:'%an')
          echo "author_name=$author_name" >> $GITHUB_ENV
          echo "Author: $author_name"

      - name: Send success or error based on status code
        if: success()
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          
          status_code="${{ steps.regions_request.outputs.status }}"
          
          if [ "$status_code" -eq 200 ]; then
            echo "Status is 200, sending success notification to Telegram."
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
              -d chat_id=$TELEGRAM_CHAT_ID \
              -d text="&lt;b&gt;✅ Деплой прошел успешно!&lt;/b&gt;%0A&lt;b&gt;Статус:&lt;/b&gt; 200%0A&lt;b&gt;Коммит:&lt;/b&gt; &lt;code&gt;$GITHUB_SHA&lt;/code&gt;%0A&lt;b&gt;Автор:&lt;/b&gt; ${{ env.author_name }}%0A&lt;b&gt;Ветка:&lt;/b&gt; $branch_name" \
              -d parse_mode="HTML"
          else
            echo "Status is not 200, sending failure notification to Telegram."
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
              -d chat_id=$TELEGRAM_CHAT_ID \
              -d text="&lt;b&gt;❌ Ошибка деплоя!&lt;/b&gt;%0A&lt;b&gt;Статус:&lt;/b&gt; $status_code%0A&lt;b&gt;Коммит:&lt;/b&gt; &lt;code&gt;$GITHUB_SHA&lt;/code&gt;%0A&lt;b&gt;Автор:&lt;/b&gt; ${{ env.author_name }}%0A&lt;b&gt;Ветка:&lt;/b&gt; $branch_name%0A%0A&lt;b&gt;&lt;a href=&quot;https://github.com/d2avids/rso/actions&quot;&gt;Смотреть подробнее&lt;/a&gt;&lt;/b&gt;" \
              -d parse_mode="HTML"
          fi

      - name: Send workflow failure notification
        if: failure()
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          
          echo "Workflow error, sending failure notification to Telegram."
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="<b>❌ Ошибка деплоя!</b>%0A<b>Статус:</b> Workflow error%0A<b>Коммит:</b> <code>$GITHUB_SHA</code>%0A<b>Автор:</b> ${{ env.author_name }}%0A<b>Ветка:</b> $branch_name%0A%0A<b><a href=\"https://github.com/d2avids/rso/actions\">Смотреть подробнее</a></b>" \
            -d parse_mode="HTML"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
