# Generated by Django 4.2.7 on 2024-03-25 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0014_q4tandemranking_q4ranking_q3tandemranking_q3ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q15Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Q15Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=300, verbose_name='Ссылка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='q3ranking',
            options={'verbose_name': 'Место по 3 показателю', 'verbose_name_plural': 'Места по 3 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q3tandemranking',
            options={'verbose_name': 'Тандем-место по 3 показателю', 'verbose_name_plural': 'Тандем-места по 3 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q4ranking',
            options={'verbose_name': 'Место по 4 показателю', 'verbose_name_plural': 'Места по 4 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q4tandemranking',
            options={'verbose_name': 'Тандем-место по 4 показателю', 'verbose_name_plural': 'Тандем-места по 4 показателю'},
        ),
        migrations.CreateModel(
            name='Q15TandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.FloatField(verbose_name='Итоговое место по показателю в тандеме')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'verbose_name': 'Тандем-место по 15 показателю',
                'verbose_name_plural': 'Тандем-места по 15 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q15Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Место по 15 показателю',
                'verbose_name_plural': 'Места по 15 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q15DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
                ('q15_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q15_event', to='competitions.q15event', verbose_name='Название источника статьи')),
                ('q15_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q15_link', to='competitions.q15link', verbose_name='Ссылка на статью об участии отряда')),
            ],
            options={
                'verbose_name': 'Отчет по 15 показателю',
                'verbose_name_plural': 'Отчеты по 15 показателю',
            },
        ),
        migrations.AddConstraint(
            model_name='q15detachmentreport',
            constraint=models.UniqueConstraint(fields=('q15_event', 'q15_link'), name='unique_q15_event_link'),
        ),
    ]
