# Generated by Django 4.2.7 on 2024-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_alter_q5educatedparticipant_document'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='q17detachmentreport',
            constraint=models.UniqueConstraint(fields=('q17_link', 'detachment'), name='unique_link_detachment_q17detachmentreport'),
        ),
    ]
