# Generated by Django 4.2.7 on 2024-03-30 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0031_alter_regionalheadquarter_requisites"),
        ("competitions", "0019_alter_q5educatedparticipant_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Q16TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 16"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тандем-место по 16 показателю",
                "verbose_name_plural": "Тандем-места по 16 показателю",
            },
        ),
        migrations.CreateModel(
            name="Q16Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "link_vk_commander",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Ссылка на vk командира",
                    ),
                ),
                (
                    "link_vk_commissar",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Ссылка на vk комиссара",
                    ),
                ),
                (
                    "vk_rso_number_subscribers",
                    models.PositiveSmallIntegerField(
                        default=0,
                        verbose_name="Количество подписок на страницу RSO в vk",
                    ),
                ),
                (
                    "link_vk_detachment",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Ссылка на vk отряда",
                    ),
                ),
                (
                    "vk_detachment_number_subscribers",
                    models.PositiveSmallIntegerField(
                        verbose_name="Количество подписок на страницу отряда в vk"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Очки"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет по 16 показателю",
                "verbose_name_plural": "Отчеты по 16 показателю",
            },
        ),
        migrations.CreateModel(
            name="Q16Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 16"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место по 16 показателю",
                "verbose_name_plural": "Места по 16 показателю",
            },
        ),
    ]
