# Generated by Django 4.2.7 on 2024-03-30 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0020_q16tandemranking_q16report_q16ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="q16report",
            name="june_15_detachment_members",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="q16report",
            name="vk_detachment_number_subscribers",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество подписок на страницу отряда в vk"
            ),
        ),
        migrations.AlterField(
            model_name="q16report",
            name="vk_rso_number_subscribers",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Количество участников подписанных на страницу RSO в vk",
            ),
        ),
    ]
