# Generated by Django 4.2.7 on 2024-03-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_q17detachmentreport_unique_link_detachment_q17detachmentreport'),
        ('competitions', '0021_q16report_june_15_detachment_members_and_more'),
    ]

    operations = [
    ]
