# Generated by Django 4.2.7 on 2024-03-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_merge_20240330_1831'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='q17detachmentreport',
            name='unique_link_detachment_q17detachmentreport',
        ),
    ]
