# Generated by Django 4.2.7 on 2024-03-30 19:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0031_alter_regionalheadquarter_requisites'),
        ('competitions', '0023_remove_q17detachmentreport_unique_link_detachment_q17detachmentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q14LaborProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=150)),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество бойцов, отработавших в летнем трудовом семестре')),
            ],
        ),
        migrations.CreateModel(
            name='Q14TandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.FloatField(verbose_name='Итоговое место по показателю в тандеме')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'verbose_name': 'Тандем-место по 14 показателю',
                'verbose_name_plural': 'Тандем-места по 14 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q14Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Место по 14 показателю',
                'verbose_name_plural': 'Места по 14 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q14DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
                ('q14_labor_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q14_labor_project', to='competitions.q14laborproject', verbose_name='Участники трудового проекта')),
            ],
            options={
                'verbose_name': 'Отчет по 14 показателю',
                'verbose_name_plural': 'Отчеты по 14 показателю',
            },
        ),
    ]
