# Generated by Django 4.2.7 on 2024-03-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_q14laborproject_q14tandemranking_q14ranking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q14laborproject',
            old_name='source_name',
            new_name='lab_project_name',
        ),
    ]
