# Generated by Django 4.2.7 on 2024-03-30 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0031_alter_regionalheadquarter_requisites'),
        ('competitions', '0025_rename_source_name_q14laborproject_lab_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q5ranking',
            options={'verbose_name': 'Места по 5 показателю', 'verbose_name_plural': 'Места по 5 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q5tandemranking',
            options={'verbose_name': 'Тандем-места по 5 показателю', 'verbose_name_plural': 'Тандем-места по 5 показателю'},
        ),
        migrations.CreateModel(
            name='Q6TandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 6')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'verbose_name': 'Тандем-место по 6 показателю',
                'verbose_name_plural': 'Тандем-места по 6 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q6Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 6')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Место по 6 показателю',
                'verbose_name_plural': 'Места по 6 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q6DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('first_may_demonstration', models.BooleanField(default=False)),
                ('first_may_demonstration_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('patriotic_action', models.BooleanField(default=False)),
                ('patriotic_action_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('safety_work_week', models.BooleanField(default=False)),
                ('safety_work_week_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('commander_commissioner_school', models.BooleanField(default=False)),
                ('commander_commissioner_school_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('working_semester_opening', models.BooleanField(default=False)),
                ('working_semester_opening_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('spartakiad', models.BooleanField(default=False)),
                ('spartakiad_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('professional_competition', models.BooleanField(default=False)),
                ('professional_competition_participants', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Отчет по 6 показателю',
                'verbose_name_plural': 'Отчеты по 6 показателю',
            },
        ),
    ]
