# Generated by Django 4.2.7 on 2024-03-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_alter_q5ranking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='commander_commissioner_school_participants',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='professional_competition_participants',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='safety_work_week_participants',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='spartakiad_participants',
        ),
    ]
