# Generated by Django 4.2.7 on 2024-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_remove_q6detachmentreport_commander_commissioner_school_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='q14detachmentreport',
            name='june_15_detachment_members',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='q14detachmentreport',
            name='score',
            field=models.FloatField(default=1000, verbose_name='Очки'),
        ),
    ]
