# Generated by Django 4.2.7 on 2024-03-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0031_alter_regionalheadquarter_requisites'),
        ('competitions', '0027_remove_q6detachmentreport_commander_commissioner_school_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q15DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Отчет по 5 показателю',
                'verbose_name_plural': 'Отчеты по 5 показателю',
            },
        ),
        migrations.AddField(
            model_name='q6detachmentreport',
            name='april_1_detachment_members',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Q15TandemRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 15')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'verbose_name': 'Тандем-место по 15 показателю',
                'verbose_name_plural': 'Тандем-места по 15 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q15Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 15')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Место по 15 показателю',
                'verbose_name_plural': 'Места по 15 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q15GrantWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Полное наименование грантового проекта')),
                ('status', models.CharField(choices=[('Региональный', 'Региональный'), ('Окружной', 'Окружной'), ('Всероссийский', 'Всероссийский')], max_length=25, verbose_name='Статус конкурса')),
                ('competition_link', models.URLField(max_length=300, verbose_name='Ссылка на конкурс')),
                ('prove_link', models.URLField(max_length=300, verbose_name='Ссылка на новостной источник с упоминанием победы')),
                ('is_verified', models.BooleanField(default=False)),
                ('detachment_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.q15detachmentreport', verbose_name='Отчет')),
            ],
        ),
    ]
