# Generated by Django 4.2.7 on 2024-03-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_q14detachmentreport_june_15_detachment_members_and_more'),
        ('competitions', '0028_q15detachmentreport_and_more'),
    ]

    operations = [
    ]
