# Generated by Django 4.2.7 on 2024-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_merge_20240331_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q15detachmentreport',
            options={'verbose_name': 'Отчет по 15 показателю', 'verbose_name_plural': 'Отчеты по 15 показателю'},
        ),
        migrations.AddField(
            model_name='q15detachmentreport',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очки'),
        ),
    ]
