# Generated by Django 4.2.7 on 2024-03-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_alter_q15detachmentreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q6ranking',
            name='place',
            field=models.FloatField(verbose_name='Итоговое место по показателю 6'),
        ),
        migrations.AlterField(
            model_name='q6tandemranking',
            name='place',
            field=models.FloatField(verbose_name='Итоговое место по показателю 6'),
        ),
    ]
