# Generated by Django 4.2.7 on 2024-04-01 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_alter_q6ranking_place_alter_q6tandemranking_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='q6detachmentreport',
            name='creative_festival',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='april_1_detachment_members',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='commander_commissioner_school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='first_may_demonstration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='first_may_demonstration_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='patriotic_action',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='patriotic_action_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='professional_competition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='spartakiad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='working_semester_opening',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='working_semester_opening_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
