# Generated by Django 4.2.7 on 2024-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_q6detachmentreport_creative_festival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='safety_work_week',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
