# Generated by Django 4.2.7 on 2024-04-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_alter_q6detachmentreport_safety_work_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='q6detachmentreport',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
