# Generated by Django 4.2.7 on 2024-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_q6detachmentreport_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q13detachmentreport',
            options={'verbose_name': 'Места по 13 показателю', 'verbose_name_plural': 'Места по 13 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q5detachmentreport',
            options={'verbose_name': 'Отчет по 5 показателю', 'verbose_name_plural': 'Отчеты по 5 показателю'},
        ),
        migrations.RemoveConstraint(
            model_name='q13detachmentreport',
            name='unique_report_q13detachmentreport',
        ),
        migrations.RemoveConstraint(
            model_name='q5detachmentreport',
            name='unique_report_q5detachmentreport',
        ),
        migrations.AlterField(
            model_name='q6ranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 6'),
        ),
        migrations.AlterField(
            model_name='q6tandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 6'),
        ),
    ]
