# Generated by Django 4.2.7 on 2024-04-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0032_alter_position_name'),
        ('competitions', '0035_alter_q13detachmentreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallTandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_sum', models.FloatField()),
                ('place', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
        ),
        migrations.CreateModel(
            name='OverallRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_sum', models.FloatField()),
                ('place', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
        ),
        migrations.AddConstraint(
            model_name='overalltandemranking',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment', 'junior_detachment'), name='unique_tandem_ranking_overall'),
        ),
        migrations.AddConstraint(
            model_name='overalltandemranking',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_main_ranking_overall'),
        ),
        migrations.AddConstraint(
            model_name='overalltandemranking',
            constraint=models.UniqueConstraint(fields=('competition', 'junior_detachment'), name='unique_junior_ranking_overall'),
        ),
        migrations.AddConstraint(
            model_name='overallranking',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_overall_ranking'),
        ),
    ]
