# Generated by Django 4.2.7 on 2024-04-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0036_overalltandemranking_overallranking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overallranking',
            options={'verbose_name': 'Итоговое индивидуальное место', 'verbose_name_plural': 'Итоговые индивидуальные места'},
        ),
        migrations.AlterModelOptions(
            name='overalltandemranking',
            options={'verbose_name': 'Итоговое тандем место', 'verbose_name_plural': 'Итоговые тандем места'},
        ),
        migrations.AlterField(
            model_name='overallranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Финальное место'),
        ),
        migrations.AlterField(
            model_name='overallranking',
            name='places_sum',
            field=models.FloatField(verbose_name='Сумма мест по всем показателям'),
        ),
        migrations.AlterField(
            model_name='overalltandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Финальное место'),
        ),
        migrations.AlterField(
            model_name='overalltandemranking',
            name='places_sum',
            field=models.FloatField(verbose_name='Сумма мест по всем показателям'),
        ),
    ]
