# Generated by Django 4.2.7 on 2024-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0037_alter_overallranking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='q15grantwinner',
            name='author_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор проекта'),
        ),
    ]
