# Generated by Django 4.2.7 on 2024-04-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0038_q15grantwinner_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q17EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=500, verbose_name='Название источника')),
                ('link', models.URLField(max_length=300, verbose_name='Ссылка')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='q17detachmentreport',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='q17detachmentreport',
            name='q17_event',
        ),
        migrations.RemoveField(
            model_name='q17detachmentreport',
            name='q17_link',
        ),
        migrations.DeleteModel(
            name='Q17Event',
        ),
        migrations.DeleteModel(
            name='Q17Link',
        ),
        migrations.AddField(
            model_name='q17eventlink',
            name='detachment_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q17_event_links', to='competitions.q17detachmentreport', verbose_name='Отчет по 17 показателю'),
        ),
    ]
