# Generated by Django 4.2.7 on 2024-04-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_q17eventlink_remove_q17detachmentreport_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q13detachmentreport',
            options={'verbose_name': 'Отчёт по 13 показателю', 'verbose_name_plural': 'Отчёты по 13 показателю'},
        ),
        migrations.RemoveField(
            model_name='q14detachmentreport',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='q14detachmentreport',
            name='q14_labor_project',
        ),
        migrations.AddField(
            model_name='q14laborproject',
            name='detachment_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='q14_labor_project', to='competitions.q14detachmentreport', verbose_name='Отчет по 14 показателю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='q14laborproject',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
