# Generated by Django 4.2.7 on 2024-04-07 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_q17eventlink_remove_q17detachmentreport_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryQ14LaborProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_project_name', models.CharField(max_length=150)),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество бойцов, отработавших в летнем трудовом семестре')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='q13detachmentreport',
            options={'verbose_name': 'Отчёт по 13 показателю', 'verbose_name_plural': 'Отчёты по 13 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q18detachmentreport',
            options={'verbose_name': 'Отчет по 18 показателю', 'verbose_name_plural': 'Отчеты по 18 показателю'},
        ),
        migrations.RemoveConstraint(
            model_name='q18detachmentreport',
            name='unique_report_q18detachmentreport',
        ),
        migrations.RemoveField(
            model_name='q14detachmentreport',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='q14detachmentreport',
            name='q14_labor_project',
        ),
        migrations.AddField(
            model_name='q14laborproject',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporaryq14laborproject',
            name='detachment_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q14_labor_project', to='competitions.q14detachmentreport', verbose_name='Отчет по 14 показателю'),
        ),
    ]
