# Generated by Django 4.2.7 on 2024-04-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0040_temporaryq14laborproject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Q14LaborProject',
        ),
    ]
