# Generated by Django 4.2.7 on 2024-04-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0040_alter_q13detachmentreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q18detachmentreport',
            options={'verbose_name': 'Отчет по 18 показателю', 'verbose_name_plural': 'Отчеты по 18 показателю'},
        ),
        migrations.RemoveConstraint(
            model_name='q18detachmentreport',
            name='unique_report_q18detachmentreport',
        ),
    ]
