# Generated by Django 4.2.7 on 2024-04-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_delete_q14laborproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryQ14LaborProject',
            new_name='Q14LaborProject',
        ),
    ]
