# Generated by Django 4.2.7 on 2024-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0042_rename_temporaryq14laborproject_q14laborproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q13detachmentreport',
            options={'verbose_name': 'Отчет по 13 показателю', 'verbose_name_plural': 'Отчеты по 13 показателю'},
        ),
    ]
