# Generated by Django 4.2.7 on 2024-04-23 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0032_alter_position_name'),
        ('competitions', '0043_alter_q13detachmentreport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Номер верифицируемого показателя')),
                ('action', models.CharField(choices=[('Верифицировал', 'Accepted'), ('Отклонил', 'Rejected')], max_length=25, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время действия')),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_logs', to='competitions.competitions', verbose_name='Конкурс')),
                ('verified_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_verified', to='headquarters.detachment', verbose_name='Верифицируемый отряд')),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_verified', to=settings.AUTH_USER_MODEL, verbose_name='Верифицируемый пользователь')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_verifier', to=settings.AUTH_USER_MODEL, verbose_name='Верифицирующее лицо')),
            ],
            options={
                'verbose_name': 'Лог верификации показателя',
                'verbose_name_plural': 'Логи верификаций показателей',
            },
        ),
    ]
