# Generated by Django 4.2.7 on 2024-04-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0044_qverificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qverificationlog',
            name='verified_user',
        ),
    ]
