# Generated by Django 4.2.7 on 2024-04-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0045_remove_qverificationlog_verified_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qverificationlog',
            old_name='competition_id',
            new_name='competition',
        ),
    ]
