# Generated by Django 4.2.7 on 2024-05-04 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0046_rename_competition_id_qverificationlog_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='first_may_demonstration_participants',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='patriotic_action_participants',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='q6detachmentreport',
            name='working_semester_opening_participants',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
