# Generated by Django 4.2.7 on 2024-05-17 17:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0047_alter_q6detachmentreport_first_may_demonstration_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='commander_commissioner_school',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='creative_festival',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='first_may_demonstration',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='first_may_demonstration_participants',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='patriotic_action',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='patriotic_action_participants',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='professional_competition',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='safety_work_week',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='spartakiad',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='working_semester_opening',
        ),
        migrations.RemoveField(
            model_name='q6detachmentreport',
            name='working_semester_opening_participants',
        ),
        migrations.CreateModel(
            name='WorkingSemesterOpeningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_semester_opening', models.BooleanField(default=False)),
                ('working_semester_opening_participants', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_semester_opening_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='SpartakiadBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spartakiad', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spartakiad_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyWorkWeekBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_work_week', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_work_week_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCompetitionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_competition', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_competition_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='PatrioticActionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patriotic_action', models.BooleanField(default=False)),
                ('patriotic_action_participants', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patriotic_action_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='DemonstrationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_may_demonstration', models.BooleanField(default=False)),
                ('first_may_demonstration_participants', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeFestivalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_festival', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative_festival_block', to='competitions.q6detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='CommanderCommissionerSchoolBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_commissioner_school', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commander_commissioner_school_block', to='competitions.q6detachmentreport')),
            ],
        ),
    ]
