# Generated by Django 4.2.7 on 2024-05-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0048_remove_q6detachmentreport_commander_commissioner_school_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandercommissionerschoolblock',
            options={'verbose_name': '6 показатель - отчет по блоку университета командира и комиссара', 'verbose_name_plural': '6 показатель - отчеты по блоку университета командира и комиссара'},
        ),
        migrations.AlterModelOptions(
            name='creativefestivalblock',
            options={'verbose_name': '6 показатель - отчет по блоку трудовой недели', 'verbose_name_plural': '6 показатель - отчеты по блоку трудовой недели'},
        ),
        migrations.AlterModelOptions(
            name='demonstrationblock',
            options={'verbose_name': '6 показатель - отчет по первомайской демонстрации', 'verbose_name_plural': '6 показатель - отчеты по первомайской демонстрации'},
        ),
        migrations.AlterModelOptions(
            name='patrioticactionblock',
            options={'verbose_name': '6 показатель - отчет по патриотическому блоку', 'verbose_name_plural': '6 показатель - отчеты по патриотическому блоку'},
        ),
        migrations.AlterModelOptions(
            name='professionalcompetitionblock',
            options={'verbose_name': '6 показатель - отчет по блоку профессионального конкурса', 'verbose_name_plural': '6 показатель - отчеты по блоку профессионального конкурса'},
        ),
        migrations.AlterModelOptions(
            name='safetyworkweekblock',
            options={'verbose_name': '6 показатель - отчет по блоку охраны труда', 'verbose_name_plural': '6 показатель - отчеты по блоку охраны труда'},
        ),
        migrations.AlterModelOptions(
            name='spartakiadblock',
            options={'verbose_name': '6 показатель - отчет по спартакиаде', 'verbose_name_plural': '6 показатель - отчеты по спартакиаде'},
        ),
        migrations.AlterModelOptions(
            name='workingsemesteropeningblock',
            options={'verbose_name': '6 показатель - отчет по блоку трудовой недели', 'verbose_name_plural': '6 показатель - отчеты по блоку трудовой недели'},
        ),
    ]
