# Generated by Django 4.2.7 on 2024-05-23 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0049_alter_commandercommissionerschoolblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q19tandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Итоговое место по показателю 19'),
        ),
    ]
