# Generated by Django 4.2.7 on 2024-07-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0034_alter_usercentralheadquarterposition_position_and_more'),
        ('competitions', '0051_alter_q19tandemranking_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='July15Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField(verbose_name='Количество участников')),
                ('detachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='july_15_participants', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Кол-во участников в отряде на 15 июля',
                'verbose_name_plural': 'Кол-во участников в отрядах на 15 июля',
            },
        ),
    ]
