# Generated by Django 4.2.7 on 2024-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0052_july15participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='july15participant',
            name='participants_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество участников'),
        ),
    ]
