# Generated by Django 4.2.7 on 2024-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0053_alter_july15participant_participants_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='july15participant',
            name='members_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество оплаченных чл. взносов'),
        ),
    ]
