# Generated by Django 4.2.7 on 2024-07-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0054_july15participant_members_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creativefestivalblock',
            options={'verbose_name': '6 показатель - отчет по блоку участия в творческом фестивале', 'verbose_name_plural': '6 показатель - отчеты по блоку участия в творческом фестивале'},
        ),
        migrations.AlterModelOptions(
            name='workingsemesteropeningblock',
            options={'verbose_name': '6 показатель - отчет по блоку трудового семестра', 'verbose_name_plural': '6 показатель - отчеты по блоку трудового семестра'},
        ),
    ]
