# Generated by Django 4.2.7 on 2024-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0054_july15participant_members_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='q13detachmentreport',
            name='score',
            field=models.FloatField(default=1000, verbose_name='Очки'),
        ),
    ]
