# Generated by Django 4.2.7 on 2024-09-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('competitions', '0055_alter_creativefestivalblock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='September15Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество участников')),
                ('members_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество оплаченных чл. взносов')),
                ('detachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sep_15_participants', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Кол-во участников в отряде на 15 сентября',
                'verbose_name_plural': 'Кол-во участников в отрядах на 15 сентября',
            },
        ),
    ]
