# Generated by Django 4.2.7 on 2024-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0056_september15participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q14detachmentreport',
            name='june_15_detachment_members',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Участники с оплаченным ЧВ на 15-ое сентября'),
        ),
    ]
