# Generated by Django 4.2.7 on 2024-09-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0036_regionalheadquarteremail'),
        ('competitions', '0057_alter_q14detachmentreport_june_15_detachment_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='TandemRankingCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_sum', models.FloatField(verbose_name='Сумма мест по всем показателям')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Финальное место')),
                ('q6_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 6')),
                ('q7_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 7')),
                ('q8_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 8')),
                ('q9_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 9')),
                ('q10_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 10')),
                ('q11_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 11')),
                ('q12_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 12')),
                ('q13_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 13')),
                ('q15_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 15')),
                ('q16_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 16')),
                ('q17_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 17')),
                ('q20_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 20')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tandem_ranking_competitions_copy', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_ranking_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_ranking_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'verbose_name': 'Резервный рейтинг Тандема (1 октября)',
                'verbose_name_plural': 'Резервные рейтинги Тандемов (1 октября)',
            },
        ),
        migrations.CreateModel(
            name='RankingCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_sum', models.FloatField(verbose_name='Сумма мест по всем показателям')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Финальное место')),
                ('q6_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 6')),
                ('q7_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 7')),
                ('q8_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 8')),
                ('q9_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 9')),
                ('q10_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 10')),
                ('q11_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 11')),
                ('q12_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 12')),
                ('q13_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 13')),
                ('q15_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 15')),
                ('q16_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 16')),
                ('q17_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 17')),
                ('q20_place', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговое место по показателю 20')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_competitions_copy', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_ranking_detachment', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Резервный рейтинг Дебют (1 октября)',
                'verbose_name_plural': 'Резервные рейтинги Дебют (1 октября)',
            },
        ),
    ]
