# Generated by Django 4.2.7 on 2024-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0057_alter_q14detachmentreport_june_15_detachment_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="q10report",
            name="score",
            field=models.FloatField(default=0, verbose_name="Очки"),
        ),
        migrations.AlterField(
            model_name="q11report",
            name="score",
            field=models.FloatField(default=0, verbose_name="Очки"),
        ),
        migrations.AlterField(
            model_name="q12report",
            name="score",
            field=models.FloatField(default=0, verbose_name="Очки"),
        ),
        migrations.AlterField(
            model_name="q9report",
            name="score",
            field=models.FloatField(default=0, verbose_name="Очки"),
        ),
    ]
