# Generated by Django 4.2.7 on 2024-09-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0058_alter_q10report_score_alter_q11report_score_and_more'),
        ('competitions', '0058_tandemrankingcopy_rankingcopy'),
    ]

    operations = [
    ]
