# Generated by Django 4.2.7 on 2024-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0059_merge_20240929_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingcopy',
            options={'verbose_name': 'Резервный рейтинг. Дебют (1 октября)', 'verbose_name_plural': 'Резервные рейтинги. Дебют (1 октября)'},
        ),
        migrations.AlterModelOptions(
            name='tandemrankingcopy',
            options={'verbose_name': 'Резервный рейтинг. Тандем (1 октября)', 'verbose_name_plural': 'Резервные рейтинги. Тандем (1 октября)'},
        ),
        migrations.AlterField(
            model_name='rankingcopy',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Финальное место'),
        ),
        migrations.AlterField(
            model_name='rankingcopy',
            name='places_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма мест по всем показателям'),
        ),
        migrations.AlterField(
            model_name='tandemrankingcopy',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Финальное место'),
        ),
        migrations.AlterField(
            model_name='tandemrankingcopy',
            name='places_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма мест по всем показателям'),
        ),
    ]
