# Generated by Django 4.2.7 on 2024-10-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0060_alter_rankingcopy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipants',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Подтвержденный участник конкурса'),
        ),
    ]
