# Generated by Django 4.2.7 on 2024-10-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0062_q13updatedtandemranking_q13updatedranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q13updatedranking',
            options={'verbose_name': 'Места по 13 показателю (АКТУАЛЬНЫЕ)', 'verbose_name_plural': 'Места по 13 показателю (АКТУАЛЬНЫЕ)'},
        ),
        migrations.AlterModelOptions(
            name='q13updatedtandemranking',
            options={'verbose_name': 'Тандем-места по 13 показателю (АКТУАЛЬНЫЕ)', 'verbose_name_plural': 'Тандем-места по 13 показателю (АКТУАЛЬНЫЕ)'},
        ),
    ]
