# Generated by Django 4.2.7 on 2024-10-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0063_alter_q13updatedranking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q13updatedtandemranking',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='q13updatedtandemranking',
            name='detachment',
        ),
        migrations.RemoveField(
            model_name='q13updatedtandemranking',
            name='junior_detachment',
        ),
        migrations.DeleteModel(
            name='Q13UpdatedRanking',
        ),
        migrations.DeleteModel(
            name='Q13UpdatedTandemRanking',
        ),
    ]
