# Generated by Django 4.2.7 on 2024-10-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0064_remove_q13updatedtandemranking_competition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='september15participant',
            options={'verbose_name': 'Кол-во участников в отряде на 30 сентября', 'verbose_name_plural': 'Кол-во участников в отрядах на 30 сентября'},
        ),
    ]
